### ISSUE TITLE
Allow to set max users by room and max rooms by Moderator

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1000]
Hi, is there the posibility to set a fixed amount of users by rooms.

For example, I want to set the maximun users for a room to 40, so the 41 user will have a warning like "Room is full"

Another and more important for me is to set a maximum ammount of rooms by user, so every user has the chance to create up to 3 rooms

Thanks!

**Comment by farhatahmad** [comment]
Hi @agustinmono,

In `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` there is a property called `defaultMaxUsers` which you can set to any number. Then do a `bbb-conf --restart` and you should be good to go. I believe there may actually be a bug where the max users is actually `defaultMaxUsers` - 1, so that might be something to watch out for

You can set the maximum amount of rooms per user through the Greenlight Admin Settings: http://docs.bigbluebutton.org/greenlight/gl-admin.html#number-of-rooms-per-user

**Comment by ali-shhabat** [comment]
what if i want to set the max amount of users per room for example room1 the max no of users can join at the same time is 50 but room 2 the max is 70 and so on
