### ISSUE TITLE
 Net::LDAP::Error (getaddrinfo: Try again): 

### ISSUE THREAD

**Issue by stephanerasset** [bigbluebutton/greenlight#1061]
Hello !
no ldap connexion possible !!!
 INFO: [5035193b-7468-4c09-93b8-83eb1b182d84] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=500 error='Net::LDAP::Error: getaddrinfo: Try again' duration=5018.50 view=0.00 db=1.94 host=greenlight 
FATAL: [5035193b-7468-4c09-93b8-83eb1b182d84]    
FATAL: [5035193b-7468-4c09-93b8-83eb1b182d84] Net::LDAP::Error (getaddrinfo: Try again): 
FATAL: [5035193b-7468-4c09-93b8-83eb1b182d84]    
FATAL: [5035193b-7468-4c09-93b8-83eb1b182d84] app/controllers/sessions_controller.rb:142:in `ldap' 
INFO: [5035193b-7468-4c09-93b8-83eb1b182d84] method=POST path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=25.15 view=15.46 db=0.23 host=greenlight 

have you more log to shearch in ??

**Comment by farhatahmad** [comment]
Hi @stephanerasset,

That is the error the the NET LDAP library that we use for LDAP connections returns. Unfortunately there isn't much more we could do since that's what the library returns to us. 

It's definitely an issue with your configuration, but I wouldn't know exactly what's causing this issue

**Comment by stephanerasset** [comment]
Hello
Thanks ! it was a configuration problème

have a good day !
