### ISSUE TITLE
LDAP provider doesn't populate email field

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/greenlight#1064]
I actually noticed this because the logs use email to identify the user, and it's blank for LDAP users:

https://github.com/bigbluebutton/greenlight/blob/84fb61500524b1be0e1a304e1d508e0d696ead90/app/controllers/rooms_controller.rb#L154

**Comment by trs80** [comment]
OK it turns out our LDAP entries don't have a mail: attribute. This will cause issues later since I can see some code indexes on email address. At least once I populate it, it updates the user when they log in again

**Comment by farhatahmad** [comment]
So we use a gem to deal with LDAP authentication. It could take any of the following fields for email:
`:mail, :email, :userPrincipalName`. If you don't have a mail attribute, are you storing the user's email at all?

**Comment by trs80** [comment]
Looks like those users don't have a userPrincipalName either, despite being in samba 4 (they were migrated from OpenLDAP which definitely did have a mail: attribute, so not sure what happened there). I'll fix that up, I guess the broader question is if you should test for the existence of mail before allowing the LDAP module to create the user.

**Comment by farhatahmad** [comment]
We don't actually enforce that an email is provided for users created through OAUTH specifically to handle Twitter (which was an authentication provider we used to support but no longer due), since the application used to only return a username and social id, not an email.

I'll close this issue, feel free to open another if you run into any other issues
