### ISSUE TITLE
Configuring Greenlight to send notifications via local SMTP server that does not require authentication

### ISSUE THREAD

**Issue by niemalsnever** [bigbluebutton/greenlight#1066]
Hello,
I have just set up a new BigBlueButton server and installed Greenlight, now I'm trying to configure it to send notifications via our local, internal SMTP server, which does not require (or support) authentication. No matter what I put for "SMTP_AUTH", I always get:
```
Checking SMTP connection: Failed
Error connecting to SMTP - wrong authentication type
```
Since there is no documentation for the SMTP settings, I don't know which value to put for "SMTP_AUTH" to say **none**.

**Comment by farhatahmad** [comment]
Hi @niemalsnever,

Are you upgraded to the latest version? If so, you should be able to set it to `none`.

The check may be broken, so even if it complains, try to test signing up with a user to see if an email sends

**Comment by user-501** [comment]
Hi, I have upgraded to the latest Greenlight docker build but I am also getting:
"Error connecting to SMTP - wrong authentication type none"
with 
SMTP_AUTH=none
I can connect over telnet port 25 and can send an email OK

**Comment by farhatahmad** [comment]
Do the emails still send even if the check fails?

**Comment by user-501** [comment]
Hi the emails are not sending.

**Comment by farhatahmad** [comment]
@user-501 You'll need to check your configuration then. Without knowing which smtp server you're using, it's a little hard to figure it out

**Comment by user-501** [comment]
Hi I have switched to Authenticated SMTP and it is now working correctly. 
the old config :
SMTP_SERVER=smtp.hostname
SMTP_PORT=25
SMTP_DOMAIN=domain
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTH=none
SMTP_STARTTLS_AUTO=
I suspect the issue is in the development.rb code below:

  # Tell Action Mailer to use smtp server, if configured
  config.action_mailer.delivery_method = ENV['SMTP_SERVER'].present? ? :smtp : :sendmail

  ActionMailer::Base.smtp_settings = {
    address: ENV['SMTP_SERVER'],
    port: ENV["SMTP_PORT"],
    domain: ENV['SMTP_DOMAIN'],
    user_name: ENV['SMTP_USERNAME'],
    password: ENV['SMTP_PASSWORD'],
    authentication: ENV['SMTP_AUTH'],
    enable_starttls_auto: ENV['SMTP_STARTTLS_AUTO'],
  }

**Comment by einhirn** [comment]
Did you set SMTP_STARTTLS_AUTO to either yes or no when trying to send without Auth? I'm using the SMTP without auth (and provided the patch to allow SMTP without auth). It seems that there is no default value used if that field is empty - and i guess that ActionMailer isn't happy about a field that's passed with an empty value...

**Comment by user-501** [comment]
Hi, I have tried setting  SMTP_STARTTLS_AUTO=yes/no and either way still does not work.
get the same error:
Checking SMTP connection: Failed
Error connecting to SMTP - wrong authentication type none

Not sure where the issue is but I am now using Auth SMTP so not a issue for me going forward. 
Thanks

**Comment by einhirn** [comment]
Ok, I'll create a pull request that also implements the change for the "check" command. I didn't do it before because I was lazy and I didn't care, because the fix worked fine in the main program (see [farhatamad's comment above](https://github.com/bigbluebutton/greenlight/issues/1066#issuecomment-603832940)) . But the check command showing an error when there probably isn't one obviously causes confusion...

**Comment by einhirn** [comment]
Here's the pull request: #1133
