### ISSUE TITLE
Historical Dashboard

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1080]
To improve, a dashboard where you, as administrator, can see by room how many attendees have entered, see duration, etc.

Is there a way right now to see that info? its stored anywhere? also, the ID from Greenlight its different from the Bigbluebutton API, where can I find that ID to create an API request. 

Thanks

**Comment by farhatahmad** [comment]
Hi @agustinmono,

Greenlight is not really meant to be a full scale monitoring system for BigBlueButton. More a front-end to manage the standard use cases. Have the stats for every room displayed has its own issues in terms of performance.

It's stored in the database so you'll need to pull it from there, because I don't think we display it anywhere

**Comment by agustinmono** [comment]
Ok! Thank you. Its documented how to connect to the database? I coudnt find where is the default user and password to reach the SQL Database, Thanks again

**Comment by farhatahmad** [comment]
Yeah just run the following commands:
```
docker exec -it greenlight -v2
bundle exec rails c
Room.find_by(uid: "ROOM ID").bbb_id
```
The last line will return the meetingID that BigBlueButton uses
