### ISSUE TITLE
user password checks

### ISSUE THREAD

**Issue by iangilmour** [bigbluebutton/greenlight#1103]
Hi,
On a clean BBB+greenlight install it looks like the checks carried out on new passwords used by users just confirm that they are at least 6 characters long.

Is there any way to enforce some additional password complexity?
e.g. define the min length, and ensure that it contains a mixture of upper/lowercase+at least one special character (e.g. %+&*-_ ), etc.

I'd like to ensure that users (on a public facing BBB+greenlight) don't simply use easy to guess passwords (e.g. passwords like: 'aaaaaa', etc. would pass the current checks).

**Comment by farhatahmad** [comment]
Hi @iangilmour 

Yeah its one of the issues that I've noticed as well. The problem is changing it to require additional security means invalidating the current passwords that are not "secure" enough. 

I haven't spent a lot a time researching for a way to do this without breaking current passwords but off the top of my head, I can't think of a way to do it.

**Comment by iangilmour** [comment]
I don't think you want to invalidate existing passwords that fail the additional complexity checks.
Existing passwords should remain valid.
You don't check them for complexity either on login, or on the **Profile->password->old password** field.
You only enforce the additional complexity checks on newly entered passwords.
If a BBB admin wants to ensure all passwords meet the new password complexity checks he performs a "Reset user password" per user.

**Comment by farhatahmad** [comment]
The correct Rails way to do it (validation on the model) I believe causes current passwords to be invalidated (which we obviously don't want to do).

Just checking for new passwords is going to result in a pretty hacky situation, but that may be our only choice in this situation.

**Comment by iangilmour** [comment]
Another alternative implementation is to tag passwords that don't meet the new complexity criteria as requiring an update, and force the user to update it on their next login attempt.
The user would have to authenticate themselves with their old password as part of the "update password" process.
You might extend this so that BBB admins who want to force users to enter a new password once a month say, could tag passwords as needing an update.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
