### ISSUE TITLE
no "room/meeting is full" message if defaultMaxUsers is configured

### ISSUE THREAD

**Issue by kinimodmeyer** [bigbluebutton/greenlight#1108]
hello together,

if you configure "defaultMaxUsers" on your server and more then the limit want to join the meeting they don´t get a message in greenlight. it is just a "refresh" after the join button.

i think a flash message would be really good to know what happend.

**Comment by farhatahmad** [comment]
Hi @kinimodmeyer 

Yes you're correct. It is a little tricky so I'll tag this as an enhancement for the time being until we have a chance to come back and take a better look at how to do this

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
