### ISSUE TITLE
Email server certificate

### ISSUE THREAD

**Issue by sotiris08** [bigbluebutton/greenlight#1120]
My email server does not have a valid certificate. That coused a lot of troubles when trying to set up the emails. In my email client I always select SSL/TLS (accept all certificates). Is there a similar option in greenlight? Thank you.

**Comment by farhatahmad** [comment]
I don't have much experience dealing with different SMTP servers. 

Can you try setting `SMTP_STARTTLS_AUTO=false` and restarting Greenlight?

**Comment by sotiris08** [comment]
I do not have time to test that now. I will try again in a few weeks.

**Comment by ArmanEsf** [comment]
hi, does any body solved this issue? because i'm getting this too after setting the SMTP variables.
output of ` docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`:

`Checking environment: Passed`
`Checking Connection: Passed`
`Checking Secret: Passed`
`Checking SMTP connection: Failed`
`Error connecting to SMTP - hostname "mail.mydomain.com" does not match the server certificate
`

this is our mail server and we published in the internet. it's not have a valid SSL but it'll open with https(a self-signed certificate),
as you can see : 

` cat .env |grep STARTTLS`:
`SMTP_STARTTLS_AUTO=false`

i set this to false but still get this error on email verification : 

![email-error](https://user-images.githubusercontent.com/24511276/81717996-7c4f6180-9490-11ea-80a4-4b1dbf37b211.jpg)

and the log(log/production.log) says : 
ERROR: [17782be5-e653-4ddd-9752-ac332562278e] Support: Error in email delivery: hostname "mail.mydomain.com" does not match the server certificate

Thanks in advance.

**Comment by sotiris08** [comment]
No almost forgot about it.

**Comment by sotiris08** [comment]
Ok. I solved the problem, kind of. Here's what to do:
1) Go to: https://myaccount.google.com/
2) Select Security --> 2-Step Verification
3) Enable 2-Step Verification (follow the instractions)
4) Then under the same tab (Security) there will be an option App password. Click it
5) Generate a password and keep it because you can not see in again.
6) Go to: https://mail.google.com/
7) Select Settings --> Settings --> Accounts and Inport
8) From the "box" "Send mail as:" find and select "Add another email address"
9) Follow the instructions on the pop-up window
9.1) You need to provide the settings for the email adress that you are trying to send email from.
9.2) Keep in mind that in the last step you will be asked to enter a pin that was send to the email address that you provided. (or just press a link that can be find in the same email)
10) In your .env file type the following settings:
`SMTP_SERVER=smtp.gmail.com`
`SMTP_PORT=587`
`SMTP_DOMAIL=gmail.com`
`SMTP_USERNAME=youremail@gmail.com`
`SMTP_PASSWORD=(THE APP PASSWORD THAT YOU GENERATED)`
`SMTP_AUTH=plain`
`SMTP_STARTTLS_AUTO=true`
`SMTP_SENDER=(YOUR NAME) <something@whatever.com>`
11) Restart
12) Let me know if it worked @ArmanEsf 
@farhatahmad I am not closing the issue because I do not think that this is the right way.

**Comment by sotiris08** [comment]
Do not ask me for GSuit. I think that it is possible, but I do not know.

**Comment by ArmanEsf** [comment]
tnx for your response @sotiris08 ,
but i'm not having problems with Gmail if you double check my issue said `mydomain.com` my scenario is : in the organization that i setup the BBB and GreenLight with their resources and published to the internet they have a mail server in their farm since it's local(that published in the internet) but have no ssl certificate.

i was wondering if i solve the SSL problem and can open the webmail with a valid certificate in browser the error will solve?
`Error connecting to SMTP - hostname "mail.mydomain.com" does not match the server certificate`
this error.

and if there is no way to use that mail server then i have to create a Gmail and name it on the Organization and use that for the verification and password recovery stuff.

tnx

**Comment by KurJay** [comment]
@sotiris08 Thanks is work but the email go into the promotion folder at gmail 

Is ok I can live for that

**Comment by sotiris08** [comment]
Your welcome @KurJay but I do not think that this method is responsible for your email ending up in the promotion folder. It must have something to do with the previous email that have been send from that email address. My email went strait in the primary folder.

**Comment by KurJay** [comment]
> Your welcome @KurJay but I do not think that this method is responsible for your email ending up in the promotion folder. It must have something to do with the previous email that have been send from that email address. My email went strait in the primary folder.

Is done now thanks

**Comment by farhatahmad** [comment]
Should be fixed in Greenlight 2.6.3. Just set `SMTP_OPENSSL_VERIFY_MODE=none` in `.env`
