### ISSUE TITLE
LDAP: Logging is incomplete

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/greenlight#1126]
Hi,

when using an LDAP backend to authenticate users, the production.log is broken:

```
INFO: [80641582-fe1a-4415-b571-db47931ba962] Support: Auth user  is attempting to login.
INFO: [80641582-fe1a-4415-b571-db47931ba962] Support:  has successfully logged in.

```

The reason is that app/controllers/sessions_controller.rb uses user.email which does not get populated by LDAP.

I see two possible solutions:

- populate user.email with LDAP
- use user.name in logging output

I cannot tell which one is better, I still do not really understand the whole code.

Thanks,

Christopher

**Comment by farhatahmad** [comment]
Hi @odenbach 

Thanks for reporting this. It's actually a issue on a bigger scale. Logging in Greenlight isn't really done in the best way possible. In this case, the user.email field isn't populated because LDAP doesn't return it. We have an internal ticket to improve our logging so I'll close this for the time being. 

Given how busy we are, I'm not quite sure when we'll get around to completing it
