### ISSUE TITLE
Improve Admin "Server Rooms" view

### ISSUE THREAD

**Issue by iangilmour** [bigbluebutton/greenlight#1147]
A few suggestions:

- I can sort Rooms by Name, Owner, and Id - why not Status? It would useful to be able to just show the currently active rooms. Most of the time those are the rooms I'm interested in.

- The room "created" info is of limited use - replace it with when the current meeting actually started, or when the last meeting finished if it's not active.

- Display the number of participants in a conf room as an additional column.

- When the mouse moves over the Room name consider displaying a list of all the participants - or, if that's not possible, show the first n participants. Or, preferred, use the room name as a link to a page that does show this information and also might include whether they were audio only or audio+video, etc.

**Comment by farhatahmad** [comment]
> I can sort Rooms by Name, Owner, and Id - why not Status? It would useful to be able to just show the currently active rooms. Most of the time those are the rooms I'm interested in.

Agreed that it would actually be the most useful sort. The issue is that unlike the 3 other columns, Status isn't stored in Greenlight's database. It's pulled dynamically from a getMeetings call to the BigBlueButton server. Since those other columns are in the database, they can be paginated and sorted at the same time. I have some ideas I need to explore on how to do it in an efficient way. Like all the other feature requests, I just need to find the time to do it

> The room "created" info is of limited use - replace it with when the current meeting actually started, or when the last meeting finished if it's not active

You're right, I think that would be a lot more useful

> Display the number of participants in a conf room as an additional column.

This kind of suffers from the same issue as the first one, but the more I think about it, the easier I think it is

> When the mouse moves over the Room name consider displaying a list of all the participants

Greenlight doesn't know who is in what room. It's possible to do this, it's just a question of how to do it without making server rooms extremely slow

I think these are all extremely valid useful requests. Hopefully we can get some time in the coming weeks to take a look at implementing them

**Comment by xpolish** [comment]
It would be nice see Running rooms, maybe some kind of filter using search.

**Comment by mbile** [comment]
Thanks @farhatahmad, This will be an amazing feature to have in Greenlight. Thank you again for the great work.

**Comment by GiorgioBart** [comment]
"Display the number of participants in a conf room as an additional column." This will be really usefull

**Comment by tarunb999** [comment]
I too would be the one to high-five 🙌 @farhatahmad if these features could be implemented.. I'll throw in a muffin & a cuppa too ;-)

**Comment by farhatahmad** [comment]
Requests 1 2 and 3 are done in v2.6.

4th one I believe should be a separate feature request

**Comment by farhatahmad** [comment]
I'd be curious to see how this works under load. For those with larger deployments, do you notice any changes in load time for Server Rooms on 2.6.1?
