### ISSUE TITLE
Looks like something went wrong on our end

### ISSUE THREAD

**Issue by rafelamer** [bigbluebutton/greenlight#1185]
I'm trying to use Big Blue Button and Greenlight with LDAP authentification. In my .env file, I have
LDAP_SERVER=127.0.0.1
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=uid
LDAP_BASE=dc=claimcenter,dc=com
LDAP_BIND_DN=cn=admin,dc=claimcenter,dc=com
LDAP_PASSWORD=xxxxxxxxxxxx
LDAP_ROLE_FIELD=ou

but, when I try to enter to greenlight and write my username and password, I get the error
_Looks like something went wrong on our end_
and in the production.log file, I get
_FATAL: [f8faed15-d989-48dc-b397-db8fa6f4e0c6] Net::LDAP::ConnectionRefusedError (Connection refused - connect(2) for 127.0.0.1:389):_ 

slapd is running in the host and id I do
telnet 127.0.0.1 389
it works correctly

Thanks.
Rafel Amer

**Comment by simonschweizer** [comment]
@rafelamer Are you using Greenlight in a Docker container?
If so, 127.0.0.1 would be the container itself, not the host system where I assume the ldap server will run on. In this case you will have to use e.g. the external ip of the host system.

**Comment by rafelamer** [comment]
Yes, I'm using Greenlight in a Docker container.
Now, I have changed 127.0.0.1 by the real IP of BBB host, 95.217.183.82 and I get the error
_Net::LDAP::Error (Operation timed out - user specified timeout)_

**Comment by simonschweizer** [comment]
@rafelamer ,

well, this looks like a firewall and/or binding issue. 

Is your ldap server bound to 127.0.0.1 or to all interfaces? You can check that on your host with netstat (e.g. `netstat -tulpn | grep :389`). 

If your ldap server is bound to all interfaces and the connection is still not working you have two choices:
a) You check/adopt the firewall configuration
b) You set the ldap server url to the gateway/host ip of the docker-compose generated network (e.g. 172.21.0.1). The problem in this case is, that this ip can change depending on the order you start different docker-compose configurations. So if you want this to work reliable you should modify the `docker-compose.yml` file and add a specific subnet ([reference](https://docs.docker.com/compose/compose-file/#ipam)). Note: Simply using the `host`-network will not work because greenlight is using the same port (80) as the nginx webserver.

So - if you want to use a local ldap server - you should first try variant a, because it's a lot easier.

**Comment by rafelamer** [comment]
Yes, it was a firewall problem. I have modified his configuration and now it works
Thank you very much
Rafel Amer
