### ISSUE TITLE
transfer greenlight data to new server

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#1192]
I installed new greenlight in new server and i try replace db folder to transfer all accounts and data but greenlight  failed!
how can i transfer accounts and rooms to the new server?

**Comment by simonschweizer** [comment]
@hmahdi-s What do you mean with "greenlight failed"?

Does the database container start? If it is rebooting all the time, there might be a permission issue (the postgres-user in the database container has no rights to access it's config and data files).

If the database is working you may have forgotten to change the bigbluebutton-api url?

Can you paste the logs of the db-container and the app-container? This would make it much simpler to find the "real" problem.

**Comment by buchacho** [comment]
I also think there is a problem with accessing the database files.1 Check permissions 2 Check the database username and password as well as the user

**Comment by hmahdi-s** [comment]
@simonschweizer @buchacho 
actually the problem was from .env file that i didn't see that.
after copy .env file and set new secret the problem was solved.
thank you

**Comment by buchacho** [comment]
> @simonschweizer @buchacho
> actually the problem was from .env file that i didn't see that.
> after copy .env file and set new secret the problem was solved.
> thank you

perfectly. I'm glad you solved your problem.

**Comment by AnthonyVidal** [comment]
@hmahdi-s  Please can you put the steps you did to move the BBB and the greenlight to another server?

**Comment by amirhnader** [comment]
> @hmahdi-s Please can you put the steps you did to move the BBB and the greenlight to another server?

Please tell the migration steps if you found. I also require it. 
Thanks

**Comment by buchacho** [comment]
привет что именно не получается?
  
>Четверг, 15 октября 2020, 11:43 +03:00 от amirhnader <notifications@github.com>:
> 
> 
>@hmahdi-s Please can you put the steps you did to move the BBB and the greenlight to another server?
Please tell the migration steps if you found. I also require it.
Thanks
—
You are receiving this because you were mentioned.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Note: This message is intended only for the use of the named recipient(s) and may contain confidential and/or proprietary information. If you are not the intended recipient, please contact the sender and delete this message. Any unauthorized use of the information contained in this message is prohibited.
---------------------------------------------------------------------------------------------------
Примечание: Это сообщение предназначено только для указанного (ых) получателя (ей), и может содержать конфиденциальную информацию. Если Вы не являетесь предполагаемым получателем, пожалуйста, свяжитесь с отправителем и удалите это сообщение. Любое несанкционированное использование информации, содержащейся в этом сообщении запрещено, а в некоторых случаях незаконно.
Это сообщение и приложения к нему могут содержать точку зрения, не совпадающую с точкой зрения БУЗ ВО ВОКБ№2

**Comment by amirhnader** [comment]
Hi,
Could you tell the migration steps ?

**Comment by buchacho** [comment]
Я не понимаю вопроса. Что Вам нужно сделать и что не получается? С какого форума Вы пишете?

  
>Четверг, 15 октября 2020, 23:56 +03:00 от amirhnader <notifications@github.com>:
> 
> 
>Hi,
>Could you tell the migration steps ?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
Note: This message is intended only for the use of the named recipient(s) and may contain confidential and/or proprietary information. If you are not the intended recipient, please contact the sender and delete this message. Any unauthorized use of the information contained in this message is prohibited.
---------------------------------------------------------------------------------------------------
Примечание: Это сообщение предназначено только для указанного (ых) получателя (ей), и может содержать конфиденциальную информацию. Если Вы не являетесь предполагаемым получателем, пожалуйста, свяжитесь с отправителем и удалите это сообщение. Любое несанкционированное использование информации, содержащейся в этом сообщении запрещено, а в некоторых случаях незаконно.
Это сообщение и приложения к нему могут содержать точку зрения, не совпадающую с точкой зрения БУЗ ВО ВОКБ№2
