### ISSUE TITLE
Greenlight without bigbluebutton?

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1201]
Hello, I want to install greenlight in a server, scalelite in another one , and multiple bigbluebutton clients in a few servers, is it possible to install greenlight with the bbb-install without installing the bigbluebutton client ?

is there a command to install just the greenlight and leave the bigbluebutton for other server?
Thanks a lot

**Comment by lkiesow** [comment]
If you want to install greenlight, just follow its installation guide at
http://docs.bigbluebutton.org/greenlight/gl-overview.html

**Comment by agustinmono** [comment]
Ok, but what are the minimun requirements for that?

**Comment by yanosz** [comment]
well... greenlight is a simple Ruby On Rails application. The requirements depend on the traffic.
I'm not aware of an explicit greenlight scaling howto. You'll probably be safe fullfilling gitlabs requirements (c.f. https://docs.gitlab.com/ee/install/requirements.html#hardware-requirements) - but gitlab is more complex and needs more CPU / RAM, due to background workers. I'd guess, that you need about 1/2 ~ 2/3 the amount of CPU and RAM.

@agustinmono I guess, it'd be fine to close this issue and move on to https://groups.google.com/forum/#!msg/bigbluebutton-setup/ - could you? Thx.

**Comment by agustinmono** [comment]
Thanks, yes, it would be ok if you move the issue.

Best,
Agustin

**Comment by agustinmono** [comment]
I need to open this issue again, becouse I want to install grennlight into a server domain.com/b and have in another server the bigbluebutton instalation, becouse I will use scalelite.

**Comment by harika1258** [comment]
It is impossible to install Greenlight in the seperate server access to your bigbluebutton server.

**Comment by aguerson** [comment]
@harika1258 
You are wrong. It is possible.
I did it !

**Comment by aguerson** [comment]
https://github.com/bigbluebutton/greenlight/issues/1859

**Comment by aguerson** [comment]
https://github.com/bigbluebutton/greenlight/issues/1472

**Comment by aguerson** [comment]
https://github.com/bigbluebutton/greenlight/issues/1112

**Comment by vignesh203** [comment]
How to connect bigbluebutton server from different greenlight server
