### ISSUE TITLE
manually disable room and recording deletion

### ISSUE THREAD

**Issue by bbbxam** [bigbluebutton/greenlight#1231]
Hi, 

Does anyone know what pieces of code do I need to edit in greenlight to manually disable the deletion of rooms and recording. I basically just want to disable the "Delete" buttons within the code.

I accessed the greenlight docker with "/bin/bash", but I dont know what files to edit at /usr/src/app.

Regards!

**Comment by farhatahmad** [comment]
Hi @bbbxam 

If you're going to customize code, you'll first want to switch to the customized version since changes aren't persistent in a docker container. Here's the steps: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Once you do that, you can remove 3 lines starting from here https://github.com/bigbluebutton/greenlight/blob/v2/app/views/shared/components/_recording_row.html.erb#L83

**Comment by bbbxam** [comment]
Thanks! Worked out pretty well.
