### ISSUE TITLE
[FQ] ldap fullname for conference

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1238]
Is it possible to select not the login name but a field like the first name or the full name from the ldap source to participate in conferences?

**Comment by farhatahmad** [comment]
This depends on a couple of things. 

1- Are you running the customized version of Greenlight? Making this change requires a code change
2- What field in your your storing the name that you want to pass in

I don't think its an easy change because of the LDAP gem that we're using

**Comment by mrkeksi** [comment]
Of course I use the configurable "version". ;) The attribute for the full name is: fullName
We also have "sn" for the last name and "givenName" for the first Name.

**Comment by farhatahmad** [comment]
@mrkeksi  Sorry, I just realized I never got back to you. It's tricky because of the LDAP gem
.
`[:displayName, :cn]` this is what's currently used to chose the user's name. We could instead change that to `givenName`

Try changing this line https://github.com/bigbluebutton/greenlight/blob/master/app/models/concerns/auth_values.rb#L28 from `auth['info']['name']` to `auth['info']['first_name']`

This should store the givenName from LDAP in the name attribute of the user, which is the name that is passed to BigBlueButton

**Comment by EinsVier** [comment]
Or the line
https://github.com/bigbluebutton/greenlight/blob/master/app/models/concerns/auth_values.rb#L28
from
`auth['info']['name']`
to
`auth['info']['first_name'] + " " + auth['info']['last_name']`

This should save the user's first name and last name from the `givenName` and `sn` LDAP attributes.
So we pass the full name to BigBlueButton

**Comment by EinsVier** [comment]
Or so from
https://github.com/bigbluebutton/greenlight/blob/3f3c69d85edef5222787cfe256d86854118c802a/app/models/concerns/auth_values.rb#L22-L30
**to**
```
  # Provider attributes.
  def auth_name(auth)
    case auth['provider']
    when :office365
      auth['info']['display_name']
    when :ldap
       auth['info']['first_name'] + " " + auth['info']['last_name']
    else
       auth['info']['name']
    end
  end

```

**Comment by mrkeksi** [comment]
Works great. Thank you both.
