### ISSUE TITLE
Docker image build with image_build.sh issue

### ISSUE THREAD

**Issue by pronichev** [bigbluebutton/greenlight#1251]
Hi!
I'm trying to build my custom image. I get the error on step 5 in https://docs.bigbluebutton.org/greenlight/gl-customize.html.
The part of STDOUT:
`Step 10/27 : RUN apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
 ---> Running in 4d1f3c2303b2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: No such file or directory
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: No such file or directory
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 30 distinct packages available`
This is because v3.7 is absent in REPO http://dl-cdn.alpinelinux.org/alpine/. 
What base image I can use instead ruby:2.5.1-alpine based on alpine v3.7
Please help.

**Comment by farhatahmad** [comment]
v3.7 appears in that repo for me and I'm also able to build the image correctly. Can you try again? Maybe there was an issue on their end

**Comment by pronichev** [comment]
I see only this versions
<img width="797" alt="Screen Shot 2020-04-10 at 00 15 48" src="https://user-images.githubusercontent.com/26221515/78927434-b956bb80-7ac0-11ea-98f0-e1c219c7d3db.png">

**Comment by farhatahmad** [comment]
Weird. Seems like certain versions are blocked from appearing for you. Can you try changing your base image to `ruby:2.5.8-alpine3.10` ?

**Comment by pronichev** [comment]
Thank you! Everything worked out

**Comment by digitalwurl** [comment]
I get the error from step 5:
root@classroom:~/greenlight# ./scripts/image_build.sh ectutors release-v2
#### Docker image ectutors:release-v2 is being built
Sending build context to Docker daemon  4.756MB
Step 1/27 : FROM ruby:2.5.8-alpine AS base
2.5.8-alpine: Pulling from library/ruby
cbdbe7a5bc2a: Pull complete 
aa8ae8202b42: Pull complete 
b21786fe7c0d: Pull complete 
f0c467355a38: Pull complete 
b609cd2ef09a: Pull complete 
Digest: sha256:89091430889b64204a059177953a96821dfae3c6c12f595b9349a0a184257fa9
Status: Downloaded newer image for ruby:2.5.8-alpine
 ---> fe9b58a53eb4
Step 2/27 : ARG RAILS_ROOT=/usr/src/app
 ---> Running in d90b14956b8b
Removing intermediate container d90b14956b8b
 ---> 4214c5b1bb3d
Step 3/27 : ENV RAILS_ENV production
 ---> Running in b819b8cc1eb9
Removing intermediate container b819b8cc1eb9
 ---> 3bc7800ed738
Step 4/27 : ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"
 ---> Running in 69b2781c9813
Removing intermediate container 69b2781c9813
 ---> 98032247d3b5
Step 5/27 : RUN mkdir -p $RAILS_ROOT
 ---> Running in 4b1ae4524b5a
Removing intermediate container 4b1ae4524b5a
 ---> ca18019c37d2
Step 6/27 : WORKDIR $RAILS_ROOT
 ---> Running in 278fc30d2e3a
Removing intermediate container 278fc30d2e3a
 ---> 03e4ccce7344
Step 7/27 : ARG BUILD_PACKAGES="build-base curl-dev git"
 ---> Running in e96d927a1fcb
Removing intermediate container e96d927a1fcb
 ---> 8c24bf96c38c
Step 8/27 : ARG DEV_PACKAGES="postgresql-dev sqlite-libs sqlite-dev yaml-dev zlib-dev nodejs yarn"
 ---> Running in cc84c312fc51
Removing intermediate container cc84c312fc51
 ---> 799270b15fb5
Step 9/27 : ARG RUBY_PACKAGES="tzdata"
 ---> Running in bbb02f319a12
Removing intermediate container bbb02f319a12
 ---> a7a8e640e26e
Step 10/27 : RUN apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
 ---> Running in c32ce92aeb7e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: network error (check Internet connection and firewall)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
2 errors; 36 distinct packages available
The command '/bin/sh -c apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2
#### Docker image for ectutors can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)
root@classroom:~/greenlight#

**Comment by fajfkyns** [comment]
> Thank you! Everything worked out

Hi man, can you please give me an advice how you solved this problem? I´m new in this all. How did you changed the base image?
