### ISSUE TITLE
Feature Request: Roomlimit for users

### ISSUE THREAD

**Issue by holzhannes** [bigbluebutton/greenlight#1266]
Allow an admin to set up a maximum room limit for individual users which is above the global limit.

**Comment by temirikov** [comment]
I also need this feature. In API methods we have some setup, when meeting created, that could limit user amount.

**Comment by farhatahmad** [comment]
I'm not sure if setting the a room limit for each individual user is the way to go. I think we would be better off setting a limit based on their current role instead

**Comment by holzhannes** [comment]
I like the Idea to set different room limits within a user role!

**Comment by cgrbrt** [comment]
We need that configuration I hope you will make it soon

**Comment by iwebsur** [comment]
A nice change would be to allow administrators to choose the maximum of roles between 1/5/10/15 + rooms

**Comment by stonerl** [comment]
I also think a room limit on a role base would be a useful addition. Here are some mock-ups:

![role_room](https://user-images.githubusercontent.com/2091312/92249836-f46fe600-eeca-11ea-99fe-cf72f10f2411.png)
![role_room_no](https://user-images.githubusercontent.com/2091312/92249844-f76ad680-eeca-11ea-89f1-af39092fcc15.png)

**Comment by Snorzze** [comment]
We the Faculty IT (Heilbronn University of Applied Science) would also highly appreciate such a feature. Setting the global limit while having a high number of users can be problematic.

**Comment by MrCapitalist** [comment]
Hi
I want this feature too
It's a useful ability to set the max users can join in each room of greenlight.
How can I deploy this feature and pass this variable to the BigBluebutton API in Greenlight?

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
