### ISSUE TITLE
No user photos from ldap

### ISSUE THREAD

**Issue by drlight17** [bigbluebutton/greenlight#1275]
Hello. I've just configured greenlight with ldap auth, but i don't see avatars stored in ldap in jpegphoto attribute. Will there be such a feature? It would be very nice to store user photos from ldap in db instead of just URLs of photos.

**Comment by farhatahmad** [comment]
Hi @drlight17 

The issue is that Greenlight currently doesn't support storing actual images, only image URLs, which is why we just ignore the jpegphoto attribute. We do have plans to implement image storage of some sort sometime in the future, just not sure exactly when

**Comment by drlight17** [comment]
Thanks for the reply! This feature would be really nice!

**Comment by ReimarBauer** [comment]
nextcloud has solved this too.
https://docs.nextcloud.com/server/13.0.0/admin_manual/configuration_user/user_auth_ldap.html#nextcloud-avatar-integration

Somehow I expect there is a webfunction available which did nothing more than requesting the  ldap  jpegphoto and creates an image url as a functional service.

**Comment by ReimarBauer** [comment]
idea from gitlab
https://github.com/brigriffin/gitlabhq/commit/b8c5ba30919c72c5d66e9090b7b89a50cec5bb24

**Comment by crsthn23** [comment]
Why dont save image in DB and in webpage put:

<img src="data:image/jpeg;base64,put_alldata_of_field_image_here">

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
