### ISSUE TITLE
A user with a role which can manage users should not be able to manage users with higher role priority

### ISSUE THREAD

**Issue by dymitar** [bigbluebutton/greenlight#1277]
Not a bug in current implementation, but a functional deficiency.
Imagine a role "Manager", who can only manage users, and the role is with lower priority than the Admin.
Currently a user with this role is able to delete a user with Admin role. 
From business point of view this is not a good idea.
In general, the role priority should limit the possibility to manage the users to users with lower priority role.

**Comment by farhatahmad** [comment]
Agreed, I think this is actually a pretty important request.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
