### ISSUE TITLE
Feature request: Pass access code as part of URL

### ISSUE THREAD

**Issue by MarcelWaldvogel** [bigbluebutton/greenlight#1303]
I would like to be able to send out room URLs which already contain the access code, e.g., in the form `https://demo.bigbluebutton.org/b/abc-def-ghi?access_code=123456`.

This is related to #1265, but independent of the increase in URL entropy, when dialin is necessary.

**Comment by farhatahmad** [comment]
Yeah I can definitely see how this could be useful. Makes it 1 less step to join a room

**Comment by MarcelWaldvogel** [comment]
Do you think the following change in [app/views/rooms/join.html.erb](https://github.com/bigbluebutton/greenlight/blob/master/app/views/rooms/join.html.erb) would do the job? If so, I would give it a try and submit a pull request.

Current:
```erb
<% valid_access_code = @room.access_code.nil? || @room.access_code.empty?
     || @room.access_code == session[:access_code] %>
```
New>
```erb
<% valid_access_code = @room.access_code.nil? || @room.access_code.empty?
     || @room.access_code == session[:access_code]
     || @room.access_code == params[:access_code] %>
```

BTW: Thanks for BigBlueButton+GreenLight!

**Comment by farhatahmad** [comment]
Yep that looks right. You may also want to change the invite link to automatically pass the access code aswell here:
https://github.com/bigbluebutton/greenlight/blob/master/app/views/rooms/show.html.erb#L44

**Comment by MarcelWaldvogel** [comment]
Adding it to the check in `join.html.erb` did not work out, as the `access_code` was not passed when POSTing the Username.

Trying to work around by setting `session[:access_code]` in the view did not work, as the cookie header was already sent by then. Trying to use a hidden input field failed as well. Anyway, the solution in the `rooms_controller.rb` is much more compact than any of these solutions would have been.

**Comment by ReimarBauer** [comment]
I like this :) makes communication to users much easier. Also it solves for some cases #1311 because user has only to enter name.

**Comment by ostasevych** [comment]
This may be also done by hashing the access code.

**Comment by MarcelWaldvogel** [comment]
What is the benefit of hashing it?

**Comment by kaystrobach** [comment]
I'd like to vote against that feature, as this makes sharing and misusing the room access links even easier.

**Comment by JulesLecuir** [comment]
@kaystrobach I understand that it makes the misusing of rooms probably easier, I agree with you. But for me, it's not a reason to vote against. There's a real need to make the user experience process easier so that people who are very new to BBB can adopt it.

Today we are moving our organization to big Blue Button, and this access code sharing is *always* a pain, and makes the migration towards this wonderful unnecessarily hard. 

A compromise I see here, that could give satisfaction to everyone here, is the following: 
>- As a room admin, I have the **choice** to either create a sharing link **with or without the access code**. This can be done with a switch to change that option in the admin interface.
>- On the switch activation, a confirmation popup (or equivalent) appears, to advise the user about the risks of sharing the access code withing the URL, and ask if the user really wants to activate the feature.

And anyways, if will always be better than now:
- **current behavior:** to give access to a room without access code, you can remove the access code. But if the URL is misused, you are trapped because you can hardly change a room's URL. So you have to fall back on an access code system. 
- **better behavior:** we can share an URL with an access code inside. If the URL is misused, then the code can be regenerated immediately, and the problem is solved.

**Comment by kaystrobach** [comment]
@JulesLecuir sry, i disagree.

maybe a way to find a compromiss is to use parts of your idea:

* instance wide setting - allow to include roomcode in uri (on / off)
* if enable greenlight can the show the combined link.
* if disabled the option is not available for the room owner

From my pov weakining the security here is a really big problem.

**Comment by JulesLecuir** [comment]
@kaystrobach You're right, this setting should actually be in the hands of only a few people who know what they are doing (so maybe the room owners themselves, rather the instance admins as you recommend), and should be disabled by design. Actually by "admin", I wanted to say "room owner" (sorry for the approximative terminology, I am not a dev, only a BBB enthusiastic user :) ). So I completely agree with your proposition!

In my organisation, our meetings are public by definition, so the access code makes simply no sense. But for your use case, I can see that access codes are a necessity :) Both points of view are acceptable. In the end, all what counts is that organisations who decide to leave the option disabled can do it, and that organisations who need to enable it can do it as well.

**Comment by kaystrobach** [comment]
I meant the maintainer with admin.

So for your use case your admin would enable the setting once for the whole instance and each room owner can then decide how the link is build.

For my use case the setting would be off - no code in url possible.

I think this would be a good solution.

**Comment by kaystrobach** [comment]
Just as a background - we also patched greenlight with nginx filters to enforce the usage of room codes across all the rooms (just JS, no ruby, but works for most of the teachers).

**Comment by JulesLecuir** [comment]
Good solution for me as well :)

**Comment by samo296** [comment]
Why are all of these closed? Did it get implemented? Where can I find information on that?

> as this makes sharing and misusing the room access links even easier.

Imo this is a non argument. Of course it makes sharing easier, that's the whole point. The fact that it makes it also easier for a malicious user to share it, doesn't prevent the misuse in the slightest. It just worsens UX for normal users without significant gain in security.

**Comment by dreamflasher** [comment]
@hadicheaito1 please reopen :)
