### ISSUE TITLE
User enter accidentally participant code instead of name

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1311]
Problem:
From time to time it happens that user accidentally enter the participant code instead of the name and then appeare with the participant code as name in the conference.

Suggestion:
Could the website check whether numbers are entered in the name field and then show a warning message?

**Comment by farhatahmad** [comment]
Yeah I don't see why not. We could actually just make a check to make sure they aren't entering the access code

**Comment by Sea444** [comment]
The more I think about it, the more I think that we shouldn't check wrong user input. No, we should check UI: Why do users enter passcode instead of their name. I will have a look at this topic next days...

**Comment by ReimarBauer** [comment]
I had this also on one case, it seemed that the entry was not cleared after entering the accesscode.

As this is a common feadback of such UIs you click another submit, because you think first time didn't work.

I'm with @Sea444 it happens likly because the UI is not giving a feedback on successful entered accesscode.

**Comment by farhatahmad** [comment]
Unfortunately, this is a small visual change that is not very high on our priority list. I welcome any developer to submit a PR to address this. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
