### ISSUE TITLE
When deleting a room, indicate the number of associated recordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#1336]
When deleting a room, the following dialog 

![image](https://user-images.githubusercontent.com/290351/79672131-55f21b00-819d-11ea-84dd-267ff53194c5.png)

states you'll loose associated recordings.   Extend this to show the number of recordings you will loose.  If there are no recordings associated with this room, omit the text about loosing recordings.

**Comment by farhatahmad** [comment]
We had this before but removed it for performance reasons. At the time it was done, it required preloading the recordings for all rooms in-order to count them.  Now that I think of it, there are easier, more efficient ways that it could be done. The number of recordings can be pulled dynamically when the modal appears, similar to how room settings is done now

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
