### ISSUE TITLE
Host Header Injection vulnerability

### ISSUE THREAD

**Issue by edukimod** [bigbluebutton/greenlight#1346]
We've been notified that /password_resets script has this host header injection vulnerability, that could lead GL user to malicious links in order to get access to their accounts. Here is the notification message:

------
Hi,

Your website is vulnerable to Host Header Injection ...

payload:>bing.com
Impact:
Whenever a user visits this URL, it will redirect them to site.com. It is used in phishing attacks.

How to reproduce this vulnerability:

    Open this URL https://bbb.moodle.com/ 
    open burp suite and scan it  and select  this URL  /b/password_resets params
    send it to repeater and change the host to bing.com &
    It will directly redirect
------

Here is a video which shows this injection in action:
https://drive.google.com/file/d/1FhIIL1xyRht8vpuG-8_gId_C6iM5M1r-/view?usp=drive_web

It only has relevance when using internal GL users.

**Comment by farhatahmad** [comment]
Hi @edukimod,

Thanks for reporting this. I'll take a look at implementing a fix for this

**Comment by farhatahmad** [comment]
So I've spent the past couple of hours trying to reproduce this and I think I have the fix for it. For the website that was demonstrated (bbb.moodle.com) HTTP was still accessible (http://bbb.moodle.com).

There is an `.env` variable that should be enabled `ENABLE_SSL=true` which forces https. Once I did that, I was no longer able to reproduce it. 

Are you the system admin for bbb.moodle.com?

**Comment by edukimod** [comment]
Hi @farhatahmad 
you're right, I added the ENABLE_SSL=true variable and it works as expected. 
Thanks!
