### ISSUE TITLE
Feature request: Show when recordings are being processed

### ISSUE THREAD

**Issue by a3nm** [bigbluebutton/greenlight#1353]
When I record a session in BBB, the recordings show up in the "Room recordings" list on Greenlight after a delay (probably caused by re-encoding). However, this process can take significant time, sometimes several hours. While this is being done, there is no confirmation at all in Greenlight that the recording is correctly being processed (and ideally some kind of progress information).

It would be better and less confusing if Greenlight could show, in the "Room recordings" list, some entries corresponding to recordings that are being processed, and some indication of when they will be done processing.

**Comment by farhatahmad** [comment]
I attempted this a while back and never got around to merging it. The problem is that the getRecordings call does not return recordings that are currently being processed, it only returns processed recordings. To get this feature to work, the getRecordings call to the BigBlueButton API would need to (optionally) return recordings being processed so that they can be displayed in Greenlight
