### ISSUE TITLE
Data disclosure: Listing of Greenlight users' full names in Page source.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#1358]
We were notified by one of our Greenlight users that the "Home"-Page of an authenticated user contains a list of all registered user's full names. This is associated with the "Share Room" feature.

Is there a way to implement the "Share Room" feature so that the user list stays on the server?

**Comment by farhatahmad** [comment]
Yeah so Shared Rooms provides the room owner with a searchable dropdown to share the room with other users in the organization. There are some small measures taken so you can't see the whole list (atleast 3 characters need to be typed for it to search), See:
http://docs.bigbluebutton.org/greenlight/gl-overview.html#manage-access

If that is a concern to you, it can be disabled through the site settings:
http://docs.bigbluebutton.org/greenlight/gl-admin.html#allow-users-to-share-rooms

**Comment by farhatahmad** [comment]
Yeah there isn't really an easy way around that. I don't claim to be an expert in GDPR, but there are tons of organizations that are GDPR compliant that allow you to search/list all the users in your current organization, which is the same thing as shared rooms. 

I figured some people would have an issue with it, which is why I allowed it to be disabled.

**Comment by farhatahmad** [comment]
Should be fixed by #2380
