### ISSUE TITLE
Keep user logged in

### ISSUE THREAD

**Issue by weeman1337** [bigbluebutton/greenlight#1422]
## Story

As an user I want to have an option to remember my login,  
so that I don't have to login again after I closed my browser and reopened it.

## Notes

It would be nice to have at least a config option for that.  
(I am using LDAP as authentication source.)

**Comment by farhatahmad** [comment]
I was thinking about this recently. It would definitely need to be configurable, but I can see the benefit of a "Stay signed in" checkbox on sign in.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
