### ISSUE TITLE
Add ability for users to add self-signed certs on pulled dockers

### ISSUE THREAD

**Issue by digitalsleuth** [bigbluebutton/greenlight#1455]
When following the documentation found here: [http://docs.bigbluebutton.org/greenlight/gl-install.html](url) there is no direction provided on how to add a self-signed cert can be added to the docker container.
As such, the last part of step 3 - Verifying configuration will fail with an SSL error message.

In order to do this, one will have to build from the Dockerfile found in this repo, then manually add commands to the Dockerfile to copy over the certs and update-ca-certificates.

I would like to ask for an option/pass-through/variable or other means be added during configuration to allow for the addition of these certs without having to build a manual docker.

And to clarify, this is not for OAuth, or for creating a cert. I already possess the certs for my internal domain, I just wish to add them to the pulled dockers so I can use https.

Cheers.

**Comment by MathieuPre** [comment]
I have lots of difficulties to install my own certificate for Greenlight. BBB is working fine with .

**Comment by klepptor** [comment]
Uh, same here: https://github.com/bigbluebutton/greenlight/issues/1642

**Comment by klepptor** [comment]
I think you can skip the verification of the ssl certificate of the BBB Server in lib/bbb_api.rb by adding

`http.verify_mode` = OpenSSL::SSL::VERIFY_NONE


to # Make  the request

But of course this shouldn't be done by just adding the line.

Is it possible to add an environment variable to enable/disable this?

**Comment by klepptor** [comment]
ok, that's not enough, I still get

> Checking environment: Passed
> Checking Connection: Failed
> Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)


after I changed the lines and build a new docker file...

**Comment by digitalsleuth** [comment]
@klepptor What you're suggesting is actually separate from the request for this issue. I'm asking for a method/mapping for the docker pulled from the docker hub to allow for easy mapping of custom certs. At first, I had to create a new Dockerfile from the existing one which added the following:
```
COPY ./myCA.pem /usr/local/share/ca-certificates/myCA.pem
COPY ./myCA.crt /usr/local/share/ca-certificates/myCA.crt
```
Then I just added a volume to the docker-compose.yml file to map one directory in the greenlight folder containing the certs to the proper location, and had to create volumes for the config directories so I don't lose my configs on restart.

To get my greenlight working, I didn't need (and you shouldn't need) the SSL bypass/verify.

**Comment by klepptor** [comment]
Sorry, I opened a similar issue and for my use case it's ok to have the ability to easily use own certs (which is the much better way!) or to simply bypass the cert verification to get rid off the failure message.

**Comment by klepptor** [comment]
@digitalsleuth Hi again! Do you have any news on this? I just did a few checks on this again and I can nearly get it to work.

*Without* building a new Dockerfile the easiest way so far for me is to add this to docker-compose.yml:

    services:
       app:
         ...
         volumes:
           ...
       # mount own certs
          - ./certs:/usr/local/share/ca-certificates
   
and then *manually* execute 

`docker exec greenlight-v2 update-ca-certificates`

This works great, but of course you have to execute it every time the container starts up manually. 

There must be a possibility to execute this command on docker-compose up:

    # update cert store
        command: sh -c "/usr/sbin/update-ca-certificates"

but this command in docker-compose.yml has no effect.

Maybe this is because I don't know enoght of Docker/Docker-Compose...

Is there any other possibility in the Greenlight code itself to execute this command? @farhatahmad

**Comment by kaihen** [comment]
@klepptor 
We don't have that problem/issue. 

We just overwriting the `ca-certificates.crt` file in the docker container (similar to the way you did it):
```
services:
    volumes:
      - ./ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
```
We just added our CA certificate to the `ca-certificates.crt` file. That solved our greenlight problems with the self-signed cert.


The [issue](https://github.com/bigbluebutton/bigbluebutton/issues/10381) of AndNovAtor isn't a greenlight issue and can besolved by adding the `ca-certificates.crt` to `/usr/share/meteor/bundle/systemd_start.sh`:
```
#!/bin/bash -e
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
```

We also need to import the certificate to truststore of java for bbb by using following commands:
```
keytool -import -alias CA -keystore /etc/ssl/certs/java/cacerts -file /etc/ssl/certs/CA.pem
```

@farhatahmad 
May these steps should be added to greenlight / bbb documentation.

**Comment by klepptor** [comment]
@kaihen Thx a lot! Sometimes the solution can be so easy! Just didn't think that way! ;)

**Comment by AndNovAtor** [comment]
Wow, I lost hope long time ago and didn't use BBB for months. @kaihen, and more @klepptor, thx a lot

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
