### ISSUE TITLE
migrate from sqlite to Postgres

### ISSUE THREAD

**Issue by yvikt** [bigbluebutton/greenlight#1464]
Hi I'm trying to migrate (converting)  as pointed in this instruction https://docs.bigbluebutton.org/greenlight/gl-config.html#converting-sqlite-database-to-postgresql-without-losing-data.
I was running GL 2.4 whith sqlite. It was installed whith bbb-install.sh.
At that moment I have clonned last (2.5) version to customize it.
I have several questions:
1. Is "converting-sqlite-database-to-postgresql-without-losing-data" instruction up to date ?
2. Where do I need to put my old sqlite db? into ./greenligt/db/production ?
3. Why do I need generate PG password, is it necessary ?
4. This command from instruction
`docker exec greenlight-v2 psql "postgresql://postgres:RANDOM_PASSWORD_REPLACE_ME@db:5432" -c 'CREATE DATABASE greenlight_production_new' `
gives me error
`root@b2:~/greenlight# docker exec greenlight-v2 psql "postgresql://postgres:75918a3040fcb4de@db:5432" -c 'CREATE DATABASE greenlight_production_new'
psql: FATAL:  password authentication failed for user "postgres"`
As you can see I changed PG password and put it into .env file and I have the same password in docker-compose.yml
5. When exactly do I need follow conwerting steps - before first using of a new app(when i have fresh install and do not open browser), or after I have working it?
Can you help me please?

**Comment by farhatahmad** [comment]
> Is "converting-sqlite-database-to-postgresql-without-losing-data" instruction up to date ?

Yes, it was written rather recently

> Where do I need to put my old sqlite db? into ./greenligt/db/production ? 

You should leave it as it currently is. The postgres db data is added at ~/greenlight/db/production-postgres

> Why do I need generate PG password, is it necessary ? 

So that Greenlight can securely communicate with the Postgres container

Looking at question 4 and 5, I think you may have gotten confused. If you currently have 2.4, you should:
- Switch to Postgres in the 2.4 folder
- Update Greenlight
- Switch to the customize version to make custom changes (https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize)

**Comment by yvikt** [comment]
Oh, thanks.
I thought that i need take my old sqlite db (from 2.4 folder) and simply copy it to my new greenlight instanse - into folder 2.5 which I just clonned, and do migrate operations there.
But as I understud, you say that I need migrate in my **old** environment, yea?

**Comment by farhatahmad** [comment]
Yeah that's correct. Migrate your old environment first before doing anything else
