### ISSUE TITLE
Merge two greenlight databases

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/greenlight#1474]
Hi,

a few weeks ago we started installing a BBB server for one department. After they were extremely satisfied with it we installed another one for the rest of the university. Some time later we found out about scalelite which we also installed. Now we would like to reintegrate the users and rooms of the first installation into the cluster.

I already tried to manually add users to the users table and rooms to the rooms table, but after that greenlight just vomited in my face when I tried to search through the users.

What exactly happens if users are created? What would be the best way to merge user and rooms tables?

Thanks,

Christopher

**Comment by farhatahmad** [comment]
Off the top of my head, I'm not quite sure what the best way to merge 2 databases is. How long is the shorter of the 2 user lists?

**Comment by odenbach** [comment]
The shorter list consists of 55 users and 194 rooms. The users are not the problem, the problem are the URLs of the rooms which have already been communicated to students. We want to consolidate both installations to one, so the hostname of the smaller system will move to the larger system (the certificate of the larger system already contains both names so that is not problem). But it is essential for the migration that the room URLs will stay the same. So we cannot just create new rooms on the larger system, we must migrate the old ones.

Do the greenlight rooms only exist in the greenlight database or is there some connection to the BBB server? Or is that connection only made if a meeting is started?

**Comment by farhatahmad** [comment]
You can create new rooms and make them function as the older rooms, though it may take some time. I think this may be the best option though since merging them is probably a lot more complex.

Say you want to "move" Room A from Old Server to New Server. Here's what you would do:
On Old Server:
```
docker exec -it greenlight-v2 bash
bundle exec rails c
Room.find_by(uid:"ROOM_ID")
```
Where `ROOM_ID` is the rooms uid which is in the format of `ahm-34a-231`
Take note of 2 fields: `room_uid` and `bbb_id` for that room.

Now, create a new room on the New Server and then on the New Server:
```
docker exec -it greenlight-v2 bash
bundle exec rails c
Room.find_by(uid:"NEW_ROOM_ID").update_attributes(room_uid: "OLD_ROOM_ID", bbb_id: "OLD_ROOM_BBB_ID")
```
Where `NEW_ROOM_ID` is the newly created rooms uid which is in the format of `ahm-34a-231`, `OLD_ROOM_ID` is the `room_uid` from the old server and `OLD_ROOM_BBB_ID` is the `bbb_id` from the old server.

You now have "moved" Room A from the Old Server to the New Server. The invitation link will be the same and any already created recordings will also be moved as well
