### ISSUE TITLE
How to modify locale strings

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/greenlight#1542]
Hi,

we use LDAP as authentication scheme. If somebody mistypes his password he is confronted with the text:

_The email and password you entered did not match our records. Try again or click Forgot Password to reset your password._

which is obviously wrong (there is no link with that name if LDAP is in use).

So we would like to change these texts in the various used languages. I found them in config/locales in the docker container greenlight-v2, but if I change them and restart Greenlight, they get reset to the default values.

How can I make such a change?

Thanks,

Christopher

**Comment by fnwbr** [comment]
Hey @odenbach, can you explain how you change the values?

If you make changes to the codebase you need to build a new Docker image, and then use said image instead of the official one. Restarting the docker containers will always revert to the official image when you are still referring to the official image in your `docker-compose.yml` file. But this is unspecific to Greenlight, but more related to Docker and how Docker images work.

---

Still, I think we could create a separate locale string for when LDAP is being used.

A first idea: Modify the following line to make use of a new, to-be-created `invalid_credentials_ldap` string - saying the same but without the "Forgot Password" part.

**Comment by farhatahmad** [comment]
I agree that the correct change here would be to create another string without the forgot password part if using oauth to sign in
