### ISSUE TITLE
Remove unsafe inline styles and scripts, include security headers

### ISSUE THREAD

**Issue by synnack** [bigbluebutton/greenlight#1544]
Scripts and styles should be restructured to be in .js and .css files separate from the HTML, so that a normal safe Content-Security-Policy can be applied:
~~~
Content-Security-Policy: default 'self'; object-src 'none'
~~~
Automatically loading code can be used by doing:
~~~
document.body.addEventListener('load', function(){
     autoload code here.... 
});
~~~

This should prevent Cross Site Scripting attacks and is generally a good idea.

Generally, some extra headers should also be added:
~~~
  add_header X-XSS-Protection "1; mode=block";
  add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
  add_header X-Permitted-Cross-Domain-Policies none; # Flash only
  add_header Referrer-Policy strict-origin; # Referrer privacy
  add_header Expect-CT 'max-age=31536000, enforce';
  add_header Feature-Policy "geolocation 'none'; camera 'self'; speaker 'self'; fullscreen 'self'; microphone 'self'; payment 'none'; autoplay 'self'; encrypted-media 'self'; display-capture 'self'";
~~~

Expect-CT goes hand in hand with ssl stapling, so stapling and verifying needs to be added:
~~~
  ssl_protocols TLSv1.2; # TLSv1.3 as well when ubuntu 20.04 is used.
  ssl_stapling on; # Requires nginx >= 1.3.7
  ssl_stapling_verify on; # Requires nginx => 1.3.7
  ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
  ssl_session_tickets off; # Requires nginx >= 1.5.9
~~~

Thank you for a great remote meeting system. I'v applied almost all of these myself already, except for the more strict Content-Security-Policy

**Comment by farhatahmad** [comment]
@synnack Thanks for the heads up and suggestions. I'll take a look to see how we can improve Greenlights security

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
