### ISSUE TITLE
setting ALLOW_MAIL_NOTIFICATIONS=false in Approval mode

### ISSUE THREAD

**Issue by makayabou** [bigbluebutton/greenlight#1595]
Hello, 
I have the following in my .env:
`ALLOW_MAIL_NOTIFICATIONS=false`  and SMTP_SERVER configured.
Users can ask for an account creation, without receiving a first veryfying email before the approval.
BUT they can't reset their password.

This double behavior is unclear in the doc:
`# Set this to true if you want GreenLight to send verification emails upon `
`# the creation of a new account `

**Comment by farhatahmad** [comment]
I agree that separating the ability to send emails and the requirement to verify your email is the better option here.

**Comment by marove2000** [comment]
In Addition to that:

When setting

ALLOW_MAIL_NOTIFICATIONS=true

All users, registered in the period where this was false, have to verify their account, otherwise their rooms are not working. Right now there is no option for that.

**Comment by lakano** [comment]
We have the same problem, and can't switch to "true" because a lot of people already registered before without this flag to "true".
There is a solution to have the Reset password link, even with ALLOW_MAIL_NOTIFICATIONS=false ? (or at least, to not force previous registered users to confirm their account email)

**Comment by decentral1se** [comment]
> I agree that separating the ability to send emails and the requirement to verify your email is the better option here.

Yes please, we changed this in our installation and didn't realise that this wasn't the case. There was a lot of confusion and a few tickets were raised ;) Would be great to have this separation in the configuration :+1:

**Comment by omiid-ad** [comment]
> Hello,
> I have the following in my .env:
> `ALLOW_MAIL_NOTIFICATIONS=false` and SMTP_SERVER configured.
> Users can ask for an account creation, without receiving a first veryfying email before the approval.
> BUT they can't reset their password.
> 
> This double behavior is unclear in the doc:
> `# Set this to true if you want GreenLight to send verification emails upon `
> `# the creation of a new account `

Same issue here. I need the forget password option, while it dosen't need to send verificarion emails to users.

Any update ?

**Comment by herzkerl** [comment]
Also, administrators can send password reset requests despite the account not having been verified yet. This was quite confusing for one of our customers.

I'd suggest not showing the 'reset user password' button and instead show a 'resend verification mail' for unverified users.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by omiid-ad** [comment]
> Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3! If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.
> 
> To find out more information on Greenlight v3, please click the following link: https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo
> 
> Thanks for your continued support!

Great news! So excited to see v3 of greenlight (The least we can expect is to fix this issue in it :) )
