### ISSUE TITLE
Error connecting to BigBlueButton server - Failed to open TCP connection to mydomain:443 (getaddrinfo: Try again)

### ISSUE THREAD

**Issue by tatangs** [bigbluebutton/greenlight#1618]
please help, after successfully installing bbb-install.sh with greenlight, I want to customize landing page greenlight. but instead it stopped at
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
and got an error
`Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - Failed to open TCP connection to mydomain:443 (getaddrinfo: Try again)`

**Comment by farhatahmad** [comment]
Can you confirm that your BigBlueButton server started up correctly and is running?

**Comment by lvarnava** [comment]
Hi! I have the same error, but the check shows that everything is fine and the moodle api works.
Greenlight 2.5.6
BigBlueButton Server 2.2.14 (1969)

```
root@bbb-1604:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Passed
```
I log in successfully, but when go to https://myserver.com/b/ed3-czm-kqqI logs show:

INFO: [xxx] Support: Auth user myuser@domain.com is attempting to login. 
INFO: [xxx] Support: myuser@domain.com has successfully logged in. 
INFO: [xxx] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=263.15 view=0.00 db=90.17 location=https://myserver.com/b/ed3-czm-kqq host=greenlight 
ERROR: [865d8625-367c-48b7-be08-5525ca6ab78b] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://myserver.com/bigbluebutton/api". Error: Failed to open TCP connection to foto.mpda.ru:443 (getaddrinfo: Try again)

**Comment by lvarnava** [comment]
I'm sorry to disturb you!
I found an error, the problem was with dns. I changed the local dns-nameserver in /etc/network/interfaces, and the Greenlight stopped working. When I returned the previous dns address, then everything worked.

**Comment by atrex123** [comment]
> Hi! I have the same error, but the check shows that everything is fine and the moodle api works.
> Greenlight 2.5.6
> BigBlueButton Server 2.2.14 (1969)
> 
> ```
> root@bbb-1604:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
> 
> Checking environment: Passed
> Checking Connection: Passed
> Checking Secret: Passed
> Checking SMTP connection: Passed
> ```
> 
> I log in successfully, but when go to https://myserver.com/b/ed3-czm-kqqI logs show:
> 
> INFO: [xxx] Support: Auth user [myuser@domain.com](mailto:myuser@domain.com) is attempting to login.
> INFO: [xxx] Support: [myuser@domain.com](mailto:myuser@domain.com) has successfully logged in.
> INFO: [xxx] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=263.15 view=0.00 db=90.17 location=https://myserver.com/b/ed3-czm-kqq host=greenlight
> ERROR: [865d8625-367c-48b7-be08-5525ca6ab78b] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://myserver.com/bigbluebutton/api". Error: Failed to open TCP connection to myserver.com:443 (getaddrinfo: Try again)

How did you resolve this? i have the same problem

**Comment by miazfa** [comment]
Same problem (sorry for my english). I have a vps, installed BBB and Greenlight ok:

$ docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

But in the /root/greenlight/log/production.log

ERROR: xxx BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://xxx/bigbluebutton/api". Error: Failed to open TCP connection to xxx:443 (Connection refused - connect(2) for "xxx" port 443) 

And the solution is: edit your /etc/hosts and be sure that put this line at the end:
ip  bbb_fullqualified_domain	bbb_domain

For example:
123.123.123.123    vps-example.vps.ovh.net	  vps-example

Reboot...et voilá

**Comment by caos30** [comment]
I've exactly the same problem... and after work around this problem during more than 3 hours i've decided to ask here... maybe someone can help me. This is the second time i install BBB. Briefly:

- i've installed and maintained working almost for a year the version 2.2 of BBB and now i'm trying to get running the version 2.3
- so, i've followed the official installation guide (script sh)
- i also have searched and attempted a dozen of other suggestions which helped other people with the "same problem" but without success (ufw, renew secrets, check hostname, endpoint... .env file settings, blah blah... ) even i can compare yet the settings on the VM running the v 2.2 of BBB, but i'm not able to find the difference
- i suppose that the problem is with some kind of "firewall" settings or network settings inside the VM, because the demo of BBB run perfect! what is not running is the call of Greenlight to the API on the same server ¿?¿? Even if i call the endpoint of the BBB API on browser it response the typical XML 200 message
- could be the problem related to docker ports settings or something like this

My log says this (greenlight/log/production.log):

`2021-07-26 05:35:42 +0000 - ERROR: [07f124be-1ac8-4387-8e6c-0e6a19f018a6] [177.228.XXX.XXX] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://bbb.mydomain.com/bigbluebutton/api". Error: Failed to open TCP connection to bbb.mydomain.com:443 (Connection refused - connect(2) for "bbb.mydomain.com" port 443) `

When i run the greenlicht CHECK command it says all is fine:

`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`

It returns:

`Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Passed`

So... i'm quite desperate ... any suggestion are very welcome!

**Comment by mrichtsfeld** [comment]
@miazfa your solution works, but that is not really how it should be defined, right? When I have a local installation the hosts file should not need the external IP, right?

Maybe the BBB team can give us an update here. Thank you

**Comment by h0jeZvgoxFepBQ2C** [comment]
I have the same issue with 2.3 installation via install script... :(

**Comment by h0jeZvgoxFepBQ2C** [comment]
I had to change my /etc/hosts and replace the 127.0.0.1 or 127.0.1.1 with the current public IP from my domain, then it worked instantly!

**Comment by vahidajorloo** [comment]
i had the same problem and the solution was editing `/etc/netplan/01-network-manager-all.yaml` and add 8.8.8.8 as a name server
then apply it using `netplan apply` command

**Comment by gabrieleMorabito** [comment]
> I had to change my /etc/hosts and replace the 127.0.0.1 or 127.0.1.1 with the current public IP from my domain, then it worked instantly!

tnks, it help me a lot!
