### ISSUE TITLE
Mixed content with profile image

### ISSUE THREAD

**Issue by RadicalPet** [bigbluebutton/greenlight#1634]
Relates to: https://github.com/bigbluebutton/greenlight/issues/1544
If a user sets a profile image url to an http site, I get a
>Your connection to this site is not fully secure

warning from the browser. I believe a `Content-Security-Policy` would block the image.
Some feedback to the user to not include http images would be nice.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
