### ISSUE TITLE
Make room_config default behaviour configurable

### ISSUE THREAD

**Issue by Niklas974** [bigbluebutton/greenlight#1686]
Since 2.6 we can configure mute-on-join, require-moderator-approval, anyone-can-start, all-join-moderator from the frontend (thank you!). See the [documentation](https://docs.bigbluebutton.org/greenlight/gl-admin.html#room-configuration).

Options for each are:
Always Enabled, Optional, Disabled

I suggest to split "Optional" into "Optional - default: enabled" and "Optional - default: disabled". And make them correspond to the parameters being configurable by the user but having a default setting as given by the administrator.

In my experience, many users don't check the options upon room creation. I would thus like to set sensible default options but leave it to the user to change them for specific purposes.

**Comment by Subdarub** [comment]
We would also be interested in this feature.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by knarrff** [comment]
I find it a little strange to close a ticket because there currently isn't time to deal with it. Would it be possible to just leave it open until either it is implemented in v3 anyway as part of the redesign or until it is added there later?

What you essentially have here is the community telling the project "Hey, we would find feature xyz useful" and the project replying "Don't have time → waste basket". The feature request is independent of v2 or v3 from a users point of view. Maybe tag it post-v3 or something to get it "out of your immediate face" for now, but please don't disregard the community talking to you by simply closing.

**Comment by farhatahmad** [comment]
@knarrff This is actually something we're already tackling as part of v3. To avoid confusion and stale issues, we're asking the community to wait until v3 is released, before recreating issues.

> community telling the project "Hey, we would find feature xyz useful" and the project replying "Don't have time → waste basket"

That's not at all what we're saying and we welcome the feedback from the community. 

What we've noticed though is that the more these issues pile up, the less and less we're able to implement them. By doing this, we're hoping to start with a clean slate so that we can give all the issues the time and respect they deserve.

All the open issues were taken into consideration for the roadmap of v3, which is why we're simply asking our community to wait until after v3, and recreating issues if needed

**Comment by trs80** [comment]
Ah, the good old CADT model: https://www.jwz.org/doc/cadt.html
