### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#1717]
As BBB support RTL layout inside rooms/meetings, It would be very nice if Greenlight support this as well.

**Comment by MortezaTaghaddomi99** [comment]
you can use rtlcss.com and change all style.css to style.rtl.css. This worked for me.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by mabras** [comment]
> To find out more information on Greenlight v3, please click the following link:

https://github.com/bigbluebutton/greenlight/issues/1686#issuecomment-1062214058
