### ISSUE TITLE
Move asset precompilation into image build process

### ISSUE THREAD

**Issue by moschlar** [bigbluebutton/greenlight#1747]
Is there a good reason to always precompile assets on container start and not on image build?

I assume it is necessary when people apply customizations by using the image as a base image or by mounting stuff into the container, but the documented solution is to modify files in git and build a new image after that, so maybe that could be improved?

**Comment by farhatahmad** [comment]
Yeah there is a specific reason for doing it and it has to do with the `RELATIVE_URL_ROOT`. Basically, Rails compiles all the assets and generates path's for said assets. The problem is that during the image build, if the Dockerfile does the precompile assets, it will always compile the assets with the path `/assets/.....` when what we need it to use is `/b/assets/...`. Now because this is based on an env variable, we can't just hardcode it to one or the other.

When I made the change, I knew there was probably a better way to do it that involved somehow passing the `RELATIVE_URL_ROOT` in the env to the Dockerfile when precompiling so that it generates the correct paths
