### ISSUE TITLE
Ldap role overwrites already set roles

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/greenlight#1755]
I'm trying to automate role assignment by creating a role defined with `LDAP_ROLE_FIELD`.

It appears that ldap roles are assigned upon login - overwriting any role set for the user beforehand.
This can result in a _loss of admin privileges_ if the admin is part of that ldap role as well, since every user can only have one role active at a time with a recent change. "Demoting" users is impossible as well, as the role is assigned again if the users logs back in.

I've locked myself out of greenlight this way and had to revert this with a local Greenlight admin account. The automated role assignment works very well, but it either has to be limited to account creation or users have to be able to have multiple roles assigned to them. It might also be enough if admin roles aren't overwritten by an ldap role.

**Comment by farhatahmad** [comment]
I'm kind of stuck in the middle between people who expect this to happen and people who don't (#1261). 

I would avoid using the LDAP role field unless you're going to exactly match the roles in Greenlight. If you plan on having users with the same LDAP role, but different Greenlight roles, then you might be better off just manually setting the roles.

**Comment by mk-hs** [comment]
Thanks for your response.
I do agree with you, it's definitely useful behaviour for automating permissions - very useful for several hundred people, which is the case for us. But since the general Admin role can't be renamed to match ldap, wouldn't it be useful to exclude it from being replaced by an ldap role?

Unfortunately, we aren't able to modify the roles within our ldap, since it's being handed down to us by an overarching network.

**Comment by mrkeksi** [comment]
We are also confronted with this behaviour. There are teachers who are assigned the role of teachers like everyone else, but some of them are supervisors of BBB. 
It would be best if higher ranks are not overwritten (maybe recognized by the number of checked options?) or it doesn't make sense to set roles manually in an LDAP environment. 

Of course we could now create extra users without role type for these teachers. But that would be cumbersome for us and the end users. And then there is the case like the previous speaker who can only create new users in a complicated way.

**Comment by playernine** [comment]
Maybe greenlight could distinguish between roles set by ldap und set locally like Admin.

Since we need to disable the Sign up feature, we need to use an ldap user as admin.
Since we are using the employeetype as LDAP_ROLE_FIELD we cannot give an mapped role the admin ablilities.
Also we can not set an employeetype attribute to the value Admin. 

So until this problem is fixed: every time we need to to some admin job we close the firewall for users, set ALLOW_GREENLIGHT_ACCOUNTS=true, restart greenlight, do the admin job, .... change back the config, restart greenlight, open the fire wall for users.

Since we want disturb the users as less as possible, we need to do that at night. And that really sucks.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
