### ISSUE TITLE
Bigbluebutton 2.2 version user registration with mobile authentication and OTP 

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1763]
Hello,

I want to integrate Bigbluebutton + greenlight - user registration with mobile authentication and OTP authentication. Can you please let me know is there any way to do that? any help is much appreciated.

**Comment by farhatahmad** [comment]
You'd need to write all the code yourself in order to get this done. I'm not aware of anyone else who's done this. This would require some pretty decent Rails knowledge as well as how the authentication works in Greenlight. You can take a look to #1334 as an example of what some of your changes could potentially look like

**Comment by createoppurtuinities** [comment]
How about can we use devise to do this authentication? I have seen the BBB on rails have this option? any insights on this?
