### ISSUE TITLE
Max login attempts enhancement

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1822]
For security reasons the max login attemps would be a great upgrade.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
