### ISSUE TITLE
Setup without docker/remote docker?

### ISSUE THREAD

**Issue by DracoMilesX** [bigbluebutton/greenlight#188]
I was wondering how to setup greenlight without docker? Currently I am using a LXC container for BBB. So while Docker is an option I prefer to use either my already existing docker installation or setup greenlight on the BBB without it.

What are the possibilities in this? Can I setup greenlight like this when my docker host is on 192.168.1.10 and my LXC container with BBB is on 192.168.1.11?

According to the BBB docs site for greenlight it says check for the steps on the github page when you don't want to install with docker. But nothing about it is mentioned here.

**Comment by ffdixon** [comment]
We'll add steps on how to setup GreenLight without using Docker.  Do you want to install it on a separate server or on the BigBlueButton server itself?

**Comment by DracoMilesX** [comment]
If installing it without docker I would like to install GreenLight on the BBB server itself. Thank you very much.

**Comment by joshua-arts** [comment]
Hey @DracoMilesX,

I've gone ahead and added [instructions for installing GreenLight without Docker](http://docs.bigbluebutton.org/install/green-light.html#installing-greenlight-without-docker) to our docs. There are quite a few steps, but most are small.

The biggest thing is that GreenLight was designed to be deployed with Docker, so we normally just pass the environment into the container. You need to move the `dotenv` gem into a production spot in the Gemfile so that GreenLight knows to use the environment file even when deployed in production.

Let me know if this works for you or you have any problems!

**Comment by DracoMilesX** [comment]
Hey @joshua-arts,

Thanks for the update. 
Checked the instructions and the install seemed to go fine. Only had to update Ruby since it was 2.3 for me.

One thing if it is possible but is it possible to run the rails command to start Greenlight as daemon/services that auto starts on boot as well?

Understandable that it is meant to be deployed with Docker but unless I was doing it wrong you have to install Docker on the BBB-server to get it working? Tried it on the proxmox connecting to the lxc container but that failed.

**Comment by joshua-arts** [comment]
Glad to hear it worked! I still have a local LXC running BigBlueButton that I sometimes use for development. I was running into the same problems that you we're when originally trying to setup GreenLight on it using Docker.

Regarding starting it on boot, I would suggest using cron. Perhaps something like this?

`@reboot cd /path/to/greenlight && rails s  -p 5000 -e production`

**Comment by DracoMilesX** [comment]
Thnxs for the response forgot about cron. It appears everything is working fine beside Ruby being a nuisance so this can be closed.

**Comment by DracoMilesX** [comment]
Just for anyone reading this you can actually just add the `-d` tag for running it as daemon

**Comment by cryptworks** [comment]
Sadly it seems that http://docs.bigbluebutton.org/install/green-light.html#installing-greenlight-without-docker appears to have been removed to only show docker as the valid method again. I also would like to see a step by step or at least the means to build an LXD to LXC container.

**Comment by datenritter** [comment]
I'd also like to install without docker.

Also, seriously, I don't think installations should rely on docker in any way. If it's "highly recommended" to use docker, that just makes me suspicious about the installation process. (Is it too complicated? Or just not documented properly? Did the developers have to tweak a lot to make it work?)

This just stopped a project on my side... Looking through github to find hints on manual dockerless installation now. :-\

**Comment by aguerson** [comment]
Hi guys,

Just search in the closed issues.
You are welcome ;)

https://github.com/bigbluebutton/greenlight/issues/1112 ( at the end )

It works in production since 3 months now !

NO pb ! Nothing to say.

I used an OpenVZ CT ( like chroot ) to install it. 

I installed my own postgres database ( it is always better to have the entire control ).

Regards,
See you later.
