### ISSUE TITLE
LDAP sync at Login

### ISSUE THREAD

**Issue by spreebits** [bigbluebutton/greenlight#1918]
Hi,

We have modified the LDAP mappings, but the change only affects new accounts and not existing ones.

We are now looking for a way to update the users, like a new LDAP sync or a data synchronization at login.

This would be an important feature.

_Originally posted by @spreebits in https://github.com/bigbluebutton/greenlight/issues/1797#issuecomment-646101303_

**Comment by inDane** [comment]
I wrote a little Python program as a workaround. It fetches uid, sn, givenName from the LDAP and puts givenName+sn as displayed name in greenlight.

https://github.com/inDane/greenlight_ldap_resync

**Comment by finkyseb** [comment]
We have the same need for people who change name and / or civility.
People can't modify his name, and there is no automatic synchronisation with the ldap.

**Comment by oxzi** [comment]
Inspired by @inDane, I wrote another small tool for LDAP synchronization which honors Greenlight's `.env` file and should be easily integrated into a "default" Docker Compose-based Greenlight installation.

<https://github.com/oxzi/greenlight-ldap-sync>

However, I would still love to see this feature upstream within Greenlight.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
