### ISSUE TITLE
Picture URL read only for LDAP users

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/greenlight#2087]
We use LDAP users only and do not want to let the users edit their profile with data that is "static" for us.
For email address and username the fields are read only, but the picture URL can be changed by
the user. Is it possible to make that field read-only (or hidden for the user)?

Armin

**Comment by farhatahmad** [comment]
If you installed Greenlight using the install-script, you'll need to make some custom changes in order to do this. 
Follow these steps first:
- https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Then you can manually change any of the Greenlight files to match your needs. For your case, change line 66 in `~/greenlight/app/views/users/components/_account.html.erb` from:
```
<%= f.text_field :image, class: "form-control #{form_is_invalid?(@user, :image)}", placeholder: t("settings.account.image_url") %>
```
to:
```
<%= f.text_field :image, class: "form-control #{form_is_invalid?(@user, :image)}", placeholder: t("settings.account.image_url"), readonly %>
```

**Comment by ArminXG** [comment]
Okay, so I need to change the code. There is no way to do it by configuration?
I expected all user fields are updated by LDAP and cannot be changed by the user. 
I really need to change the code?

**Comment by farhatahmad** [comment]
At the moment,  there's no other way
