### ISSUE TITLE
ClientTitle Change

### ISSUE THREAD

**Issue by jkjha1982** [bigbluebutton/greenlight#2120]
Hi,
I was trying to change clientTitle in BBB greenlight that appears on the navigation bar in the browser but failed even after many attempts. I had installed it using a single command (bbb.install.sh) method. Later I installed greenlight to customize. I tried following steps-
1. docker-compose down
2. Edited the title in the file "settings.yml" in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
3. ./scripts/image_build.sh bigbluebutton/greenlight release-v2
4. docker-compose up -d

Result: The title I entered appears while I am in a session/meeting but before sign in ( in page example bbb.example.com), it shows only "bigbluebutton" not my own title.

Please help.

**Comment by farhatahmad** [comment]
Greenlight sets its own page title which is why thats not working. For Greenlight, change this line:  https://github.com/bigbluebutton/greenlight/blob/master/app/views/layouts/application.html.erb#L31

From:
`<title><%= yield(:page_title).present? ? yield(:page_title) : t("bigbluebutton") %></title>`
To:
`<title>MY NEW PAGE TITLE</title>`

**Comment by jkjha1982** [comment]
Thanks a ton Farhat Ahmad!!!
It worked for me.
Regards
jkjha1982
