### ISSUE TITLE
Role or room setting that limits who can view invite links

### ISSUE THREAD

**Issue by unsnapp8** [bigbluebutton/greenlight#2176]
This' a feature request that I think this would be especially useful for schools and other education organizations to prevent abuse, higher resource usage from students creating meetings and inviting non-students, and in preventing "Zoombombing"

**Comment by farhatahmad** [comment]
Which invite links? I believe the ones in BigBlueButton are only viewable by the moderator and the other link isn't really a secret, since you must share it with other users for them to join. 

To prevent unwanted people from joining, I suggest you turn on "Require Authentication to Join" in your Site Settings
