### ISSUE TITLE
Support GDPR in GreenLight

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#219]
Similar to BigBlueButton, see

  https://github.com/bigbluebutton/bigbluebutton/issues/5438

provide two utilities to enable an organization using GreenLight to

  1. report back to a user what personal data is on the BigBlueButton server, and
  2. remove ("right to forget") all personal data related to a user from the server.

**Comment by joshua-arts** [comment]
#230 adds the ability for a user to delete their account. This removes all information about their account, rooms and sessions from the application database. Along with this, all of the rooms associated recordings are deleted from the server.

It also provides the ability to start Greenlight with a set of terms and conditions that users must agree to in order to use the application.

All of the users data is visible and editable in the settings tab, so a user can add/remove what they wish (unless it's required to use the application).
