### ISSUE TITLE
Video recordings disappeared BBB web

### ISSUE THREAD

**Issue by Sabinaakhuba** [bigbluebutton/greenlight#2192]
Hello, I have a problem with my video recordings that I took 6 days ago during the videoconference. I saw the recordings when contected to my account literally yesterday and today there are none. How can I find them?
Thank you in advance for your help.

**Comment by farhatahmad** [comment]
Greenlight doesn't store any of the recordings and instead pulls them from the BigBlueButton server. If they disappeared, its more than likely due to something on your BigBlueButton server. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
