### ISSUE TITLE
Grouping of users and rooms

### ISSUE THREAD

**Issue by HannahLeaM** [bigbluebutton/greenlight#2200]
A feature that allows you to group users and ultimatly set the permissions for a room on a group basis instead of a user basis would be highly requested. 

Root of the Problem:
  - I have multiple teachers (users) for a single location (school)
  - I have multiple rooms per school
  - Now I have to add every teacher to the rooms his school owns by hand one by one

Expected Solution:
  - Create a group based on the location (e.g.: school name)
  - Add the users to the right group
  - Set access permission for group in room settings

Synopsis:
  - Managing users and groups in a very big bbb/greenlight instance would be easier this way
  - Synoptic view is kept more easily

**Comment by farhatahmad** [comment]
Hi @HannahLeaM,

Is there a reason why you wouldn't just let the teachers create their own rooms with preset room settings?

**Comment by HannahLeaM** [comment]
Hi @farhatahmad 

Yes there is. To make is as easy as possible for our teachers and to maintain the full control over our service/server, we opted to create and manage the rooms ourselves. With this approach comes the cost of administrating everything. 

Also our user are more than unexperienced. This leeds to more problems as we give them more permissions. A trainig event would be necesarry but there is no time for this, since BigBlueButton/Greenlight is our fallback solution if the schools get closed again.

With kindest regards
Hannah Möckel

**Comment by farhatahmad** [comment]
I'd argue that full room access control in that way is a little bit out of scope for Greenlight. I'll leave this open as a feature request but considering there is a way this can already be done (even though it is a bit tedious), I don't know if we'll come around to this anytime soon

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
