### ISSUE TITLE
Display "Enter Room ID" on front page

### ISSUE THREAD

**Issue by jpetrihst** [bigbluebutton/greenlight#2228]
I'd like to suggest to display an input field on the front page where a user can just enter a room id, click on "join room" 
 and is then being redirected to the room page to enter their name and eventually join the meeting room.

For not only a few users it is asked to much to just type the room id into the url - they just don't get this right.

**Comment by farhatahmad** [comment]
I've actually been planning to rework the front page for the past while, but I haven't really got the opportunity to. You can check out this PR that does exactly what you're asking for #2142

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
