### ISSUE TITLE
Add users for which verification mails could not be sent to 'pending' and allow administrators to re-send verification mails

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2255]
I just ran into the issue that my greenlight instance could not send mail. Therefore, several users were created (blocking the name) which could never log in. These users were also not shown on the 'pending' tab. To make it easier to remediate this situation, i would suggest:

- Display users whose mail has not yet been verified in the 'pending users' tab
- Allow administrators to re-send the email verification mail for these users from the pending-users tab

**Comment by farhatahmad** [comment]
If those users try to sign in again, are they not redirected to a resend verification page?

I'm not sure if putting them on the pending tab is the right place, but I can definitely see the use of having an "Unverified" tab where the admin can either manually verify or resend a verification email

**Comment by ichdasich** [comment]
Don't know whether they are redirected; All users i did not have personal contacts with. Thing is that they probably tried that when they signed up, and it failed (as mail was still broken).

But yeah, the unverified tab would be nice.

**Comment by lonesomewalker** [comment]
Bumping this again, becomes somewhat urgent...
Several instances now seen where we can see the users in the postgre database but not visible anywhere in the system to reject/delete.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
