### ISSUE TITLE
Room sharing on user and group level

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/greenlight#2274]
Would be nice to have the room sharing feature on user and group level.

It also makes sense to select the target users from certain groups which are in the system only

**Comment by mrkeksi** [comment]
Hey @farhatahmad,

I do not know exactly how the thread creator meant it. But yesterday a customer pointed out to me how important the sharing function using LDAP groups would be. Related to school, of course, all students are stored there in classes. This would save a lot of time instead of sharing the link. I just learned in this context that there are problems even when sharing URLs, because they are embedded in PDFs or contain a line break which is then copied. Then there is "%20" in the URL between the room code and this finally results in an error 404. Of course, this is very embarrassing because you actually hope that there should be no problems, but there are also students who have just started school and or are using a tablet / computer for the first time. Also teachers are using Greenlight and BigBlueButton for the first time and not using the full potential. 
Then the sharing function would also be competitive with the Moodle system.

**Comment by CodeCrafter912** [comment]
I would love to see this too.
Chance of this being realized?

**Comment by kaystrobach** [comment]
@mrkeksi you got the point.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
