### ISSUE TITLE
Inconsistency Bootstrap assets 

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#2276]
Current [tabler](https://github.com/bigbluebutton/greenlight/blob/master/app/assets/javascripts/application.js#L31) lib use [4.0.0](https://github.com/blindsidenetworks/tabler-rubygem/blob/master/assets/javascripts/tabler/vendors/bootstrap.bundle.min.js) version of BS JavaScript asset file. The BS gem required [4.3.1](https://github.com/bigbluebutton/greenlight/blob/master/Gemfile#L62) ver. This leads to unexpected behavior and bugs.

I think replacing this
```
//= require tabler
```
with this:
```
//= require tabler/tabler
//= require popper
//= require bootstrap
//= require tabler/vendors/circle-progress.min
//= require tabler/vendors/jquery.sparkline.min
//= require tabler/core
```
will sovle it.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
