### ISSUE TITLE
Add CAS authentication

### ISSUE THREAD

**Issue by jgribonvald** [bigbluebutton/greenlight#2279]
Hi,

Are you interested by providing a PR that permit to configure the CAS auth ?

All my change are avaiblable here: https://github.com/bigbluebutton/greenlight/compare/master...GIP-RECIA:feat_auth_cas_multivalued

But there is a question on the signing.html.erb, how to manage these change when the auth type CAS provide a verified email, etc.. ?

Thanks

**Comment by jgribonvald** [comment]
In addition I'm watching to add a part for managing roles from another provided attributes. I will make an other commit, should I do it in the same PR ?

**Comment by farhatahmad** [comment]
Hi Julien,

I believe we have the authentication methods that we would like to support already in the application, with SAML support available through an external PR. Thank you for the offer

**Comment by jgribonvald** [comment]
@farhatahmad I don't understand all, you're telling that there is an external PR that permit to make auth thougth SAML ?
Ok CAS can make a SAML auth, but CAS 3.0 protocol i an offical protocol to provide user attributes, after I seen only things with shibboleth, that are really long and complexe to make when we know that no official module isn't existing for nginx. 
Also a lot of educational institutions use CAS, and already 3 peoples (from different universities) asked me how I did the CAS auth and someone on the list responded in asking to the core team to consider this contribution.
Are you sure that providing a such auth can't be integrated ? On my change provided I forgot the properties, but I just have to rewrite my commit and do a PR.
There isn't way to consider adding this auth, or to talk about that ?
It's an argument to go on building a custom UI from our side...

**Comment by mtsonline** [comment]
I also cannot understand why a PR that would bring CAS auth to greenlight should not be welcome - this seems a bit strange.
we would defenitely use it instead of ldap auth.
And yes, open ID would be the way to go but if organisations are build on cas it is a long way to go changing the auth mechanism in all applications.
cheers

**Comment by aguerson** [comment]
What @farhatahmad is trying to tell you is that he can't integrate everything into greenlight, otherwise he will have to support it. At least that's what I understand. He answered me the same way for shibboleth ;)
On the other hand you can make a clone of his repo and propose an auth CAS in it that you would maintain.
For shib I made the choice not to do PR, but just a diff. The French "bearded" community has a lot of other channels if some people want to continue ;)
