### ISSUE TITLE
Is it possible to use multiple green lights like using vhost on one server?

### ISSUE THREAD

**Issue by chh11111** [bigbluebutton/greenlight#2314]
Is it possible to use multiple green lights like using vhost on one server? 

 My system configuration scenario is like this. 

1. Configure multiple BBBs through scalelite 

 2. Setting greenlight for each domain on one server 

 3. All greenlights connect BBB with scalelite The problem here is number 2. 

 Is there a way to set multiple Greenlights for each domain on one server like VHOST? 

 If there is a way, please explain in detail and thank you in advance.

**Comment by aguerson** [comment]
Hi @chh11111 
In my case, I have one server with 3 instances scalelite inside, one server with 2 instances of greenlight. On both server, I have only one nginx to serve them.
How ? First, I by-pass docker, and I re-install the instance directly as a service on the server. I have create one account for each service with different path.
I have 

on the scalelite serv

```
/opt/bbb/scalelite_prod
/opt/bbb/scalelite_moodle
/opt/bbb/scalelite_dev
```

on the greenlight serv
```

/opt/bbb/greenlight_prod
/opt/bbb/greenlight_dev
```

You can easely do this playing with the configuration file of greenlight and/or scalelite.
In the case of greenlight, you to moove /b by another thing. Two time. In my case, one for my prod env, the other one for my dev env.

The only thing who will not work is the pre-charged presentation, because the storage lib use a link directly writted in the lib. Maybe if I rewrite the lib, I could use an other one...

I hope it is OK for you ;)
Regards,
Aurélien.

**Comment by aguerson** [comment]
One last thing, don't use Apache but definitively nginx. "/cable" only works with nginx !!

**Comment by chh11111** [comment]
Thank you for the reply.

"How? First, I bypass docker, and I re-install the instance directly as a service on the server. I have create one account for each service with different path."

<- Can you elaborate on this part?

I don't seem to understand because I'm not better than you.

BBB, Greenight, and scalelite all have been set up successfully, but how to set them all on one server like you have never thought of.

Can you tell me how to do it step by step?

**Comment by aguerson** [comment]
https://github.com/bigbluebutton/greenlight/issues/1370

https://github.com/bigbluebutton/greenlight/issues/1472

https://github.com/bigbluebutton/greenlight/issues/1859

https://github.com/blindsidenetworks/scalelite/issues/225

https://github.com/bigbluebutton/greenlight/issues/1112

A good base to begin ;)
