### ISSUE TITLE
Allow to define default presentation within greenlight

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/greenlight#2334]
If you manage a bigger installation it would make live easier to provide the default presentatin directly from greenlight.

AFAIK currently the only way to set the default presentation is to do it on each BBB Server:

* https://docs.bigbluebutton.org/2.2/customize.html#change-the-default-presentation

Or via a cluster setting in the API.

* As an greenlight admin i would like to change the default presentation for BBB rooms created with greenlight in order to make a possible for non tech people change the presentation.
* As a greenlight user i want to get my rooms prepared with the default presentation in greenlight (or if defined the custom one of the room), in order to make my participants feel comfortable.

**Comment by fireba11** [comment]
That's already implemented, you just need to enable it in settings.

**Comment by kaystrobach** [comment]
@fireba11 can you point me to the setting please?

I just found the pre upload presentation per room feature.

**Comment by erisd** [comment]
uhh, I'm also very interested in this Feature - where is that Setting?
A Greenlight wide default Presentation would be awesome!

**Comment by farhatahmad** [comment]
The feature to setup a default presentation in Greenlight isn't done yet. Only setting up a presentation per room

**Comment by kaystrobach** [comment]
Current Workaround - custom Loadbalancer which sets it

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
