### ISSUE TITLE
greenlight/docker for newbies: how to activate mailnotification

### ISSUE THREAD

**Issue by ethpi** [bigbluebutton/greenlight#2359]
Since half a year I'm running a BBB-Server with greenlight installed with `bbb-install.sh`.

Unfortunately I'm not familiar with docker. Now I tried to activate mailnotification for resetting passwords. In the file `/root/greenlight/.env` I set

`ALLOW_MAIL_NOTIFICATIONS=true`

and all those lines with

`SMTP_*`

with the hopefully correct values for my mailserver. It seems that greenlight doesn't use this settings. 

How can I manage that greenlight uses this new values? Is there a step-by-step manual to renew the greenlight docker  image and to restart greenlight?

**Comment by lonesomewalker** [comment]
Did you restart the docker container?

If you don't know how:
```cd ~/greenlight && docker-compose down && docker-compose up -d```
Just copy this to your bash.

And since NOBODY!!! should just copy&paste without knowing what happens in the background:
```cd ~/greenlight``` change directory to the homefolder of the user.
When you did this as root, login as root. When you did this as another user, log in with this account.

```docker-compose down```
In the greenlight folder is a docker-compose.yml file, which can be parsed by docker-compose.
This will shutdown your current container.

```docker-compose up -d```
Again, this will docker-compose tell to bring up all the neccessary containers defined in the yml file.
Also -d means to detach, run in background.

And if you don't know already:
```docker pull bigbluebutton/greenlight:v2 && cd ~/greenlight && docker-compose down && docker-compose up -d```
This will pull the latest stable greenlight version, shuts down and restarts the container.

Keep in mind, that the starting of the greenlight container takes some time.
Also, remember: after changing the .env file you have to run the first command EVERY TIME.

**Comment by ethpi** [comment]
Many thanks. It's really helpful that you explained each step. Great. 

I will test the steps after I made a fresh snapshot and no meeting runs and I have a lot of time. (If anything goes wrong I have a really big problem.)

**Comment by lonesomewalker** [comment]
Two things: if it is done, close this issue and related questions which are also clearly not "issues" should be asked here:
https://groups.google.com/g/bigbluebutton-setup

I just wrote you these lines for all those who will also search for that.

**Comment by ethpi** [comment]
It took a while to test. It works perfectly, many thanks.
