### ISSUE TITLE
error in step Using docker run

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/greenlight#238]
I'm running the following command

`docker run -d -p 5000:80 -v $(pwd)/db/production:/usr/src/app/db/production --env-file env --name greenlight-v2 bigbluebutton/greenlight:v2`

I encounter such a mistake
```
docker: Error response from daemon: Conflict. The container name "/greenlight-v2" is already in use by container "907f3c6e9345e6d38b129a8542e6c13149eb362d72995116f10ad115ff6a1c4d". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
Corresponding to the output of the given error
I did rename and delete, but it still issues the above error

Information that may be useful

```

root@zconf:~/greenlight# ls 
db  docker-compose.yml  env  env-old  log
root@zconf:~/greenlight# docker-compose -v
docker-compose version 1.22.0, build f46880fe
root@zconf:~/greenlight# docker -v
Docker version 18.06.0-ce, build 0ffa825
root@zconf:~/greenlight# ls -la  /var/lib/docker/containers/
total 12
drwx------  3 root root 4096 Aug 11 01:00 .
drwx--x--x 15 root root 4096 Aug 11 01:08 ..
drwx------  4 root root 4096 Aug 11 01:09 907f3c6e9345e6d38b129a8542e6c13149eb362d72995116f10ad115ff6a1c4d
root@zconf:~/greenlight# ^C
root@zconf:~/greenlight# 
```

**Comment by joshua-arts** [comment]
Hey @bijism,

The problem is exactly as the error states. You already have a container running with the name `greenlight-v2`.

There is a section in the Greenlight docs on [recreating the Greenlight container](http://docs.bigbluebutton.org/install/greenlight-v2.html#applying-env-changes). It might also be a good idea to run through some of the official documentation for managing docker containers.
