### ISSUE TITLE
Invitation email field is not validated to be an email address

### ISSUE THREAD

**Issue by hng** [bigbluebutton/greenlight#2463]
The email field from the invite user modal is not validated to actually be an email address. 

This can cause UX problems when typing in a bad formatted email address, it can also cause privacy problems as everything that is typed into the email field is saved and can be displayed on the "invited" tab.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
