### ISSUE TITLE
Optionally disable Sign Up Notifications

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/greenlight#2473]
We use greenlight with many users who can add others users. All these user get notification mails for any new user.

Please make this optionally.

And: Please dont send these mails with all recipients in "to"-field (due to privacy).

Best regards

**Comment by erisd** [comment]
For Admins in the EU this could be an GDPR Issue:
Users have a right that all data is deleted. Thats hard when a bunch of admins (and maybe old admin accounts to) have a huge user list ist their inbox (or archive or trash)

**Comment by fl4t23** [comment]
Is there a solution to the problem "disable Sign Up Notifications" for normal users

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
