### ISSUE TITLE
Language settings in Greenlight are not inherited by BBB and vice versa

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#2636]
**Describe the bug**
If I change the language in my profile in Greenlight the language of the BBB conversation remains the same. Please, make it connected.

**To Reproduce**
1. Goto Greenlight and change the language to another
2. Login to BBB
3. Observe that the language is another

**Expected behavior**
If I change the language in Greenlight it should be changed properly in BBB and vice versa.

**Actual behavior**
Language settings differ both in Greenlight and BBB and do not influence each other.

**Comment by farhatahmad** [comment]
@pedrobmarin Can you give me the parameter name?

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/0372021fba9a2b97ee26a48a14ad6db39d4c9c2f/bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js#L34

It's a userdata JOIN param: `userdata-bbb_override_default_locale`

**Comment by farhatahmad** [comment]
Hmmm.. Tried setting `userdata-bbb_override_default_locale="de_DE"` and a ton of different options and none of them seemed to work (both in Greenlight and API Mate)

**Comment by pedrobmarin** [comment]
Maybe @Tainan404 can take a look at this. As far as I know that's the correct userdata for this scenario but, indeed, it's not working.

**Comment by pedrobmarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.10

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
