### ISSUE TITLE
Email Verification System

### ISSUE THREAD

**Issue by jiama843** [bigbluebutton/greenlight#267]
Upon user signup, a verification email should be sent to the one that authorised the account. They need to verify their email address before being able to access any features.

**Comment by valerio-bozzolan** [comment]
Uhm. I don't understand the email verification system in Greenlight.

Take for example the Approve/Decline workflow. In my environment the email is never validated and administrator approve users without valid emails (because you don't know if the user has a valid email or not).

Is it something related to Greenlight 2.8.2.2?
