### ISSUE TITLE
Missing users

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#2694]
Greenlight latest version:

user has done self-registration, gl is set to approve/decline.

User clicked on validation link.

User not visible in the system and not able to login.

Row in database:
```[91, nil, "greenlight", "gl-gdfhuwgmebex", "Some Username", nil, "some.email@example.org", nil, nil, "$2a$12$tKBadJS7yxVZENBlKD9VKOXZFNxbcLkqCRNSVl7cps.C1DaaGme5S", false, Fri, 23 Apr 2021 07:44:56 UTC +00:00, Fri, 23 Apr 2021 07:46:20 UTC +00:00, false, "default", nil, nil, "aa97acec2ccef25abf07c3feff1eaca0d921291c7497575bda62e3347f2b6dc7", nil, false, nil, nil]```

Any clue what happened there?

**Comment by farhatahmad** [comment]
This is the issue you commented under (https://github.com/bigbluebutton/greenlight/issues/2255)

The user isn't verified (which I can tell from the `false` after the 2 dates), which means they're not showing up in the users table. I agree that this should probably be fixed with another tab on Manage Users

If the user tries to sign in again, can they not resend a verification message to themself?

You can also fix it manually by running this command in the console: `User.find_by(email: "____" ).activate`

**Comment by lonesomewalker** [comment]
Hi :-)

Unfortunately, totally different system with other symptoms :-/
On this instance the user is not even visible which leads to other complications...

**Comment by farhatahmad** [comment]
Are the users not in the database at all?

**Comment by lonesomewalker** [comment]
The specific user is in the database. But different from the other issue, not able to login, not able to recover pwd, not able to re-register, not able to re-invite, and the ugliest one: similar email addresses are also not able to register anymore.

Fixed this in the pgsql myself, but this is something weird... :-/

**Comment by farhatahmad** [comment]
Going to close this issue. If you can narrow down some of these instances (replication steps), please open a new issue and I'll take a look at fixing it
