### ISSUE TITLE
phpPgAdmin - Connection failed

### ISSUE THREAD

**Issue by TheJSCode** [bigbluebutton/greenlight#2710]
Hello, when I try to connect (via an external server) to the Greenlight Database with the username and password in docker-compose.yml, the connection fails. It says "Login failed."

My phpPgAdmin Config:
	```
// Display name for the server on the login screen
	$conf['servers'][0]['desc'] = 'greenlight';

	// Hostname or IP address for server.  Use '' for UNIX domain socket.
	// use 'localhost' for TCP/IP connection on this computer
	$conf['servers'][0]['host'] = '(hostname)';

	// Database port on server (5432 is the PostgreSQL default)
	$conf['servers'][0]['port'] = 5432;

	// Database SSL mode
	// Possible options: disable, allow, prefer, require
	// To require SSL on older servers use option: legacy
	// To ignore the SSL mode, use option: unspecified
	$conf['servers'][0]['sslmode'] = 'disable';

	// Change the default database only if you cannot connect to template1.
	// For a PostgreSQL 8.1+ server, you can set this to 'postgres'.
	$conf['servers'][0]['defaultdb'] = 'postgres';

	// Specify the path to the database dump utilities for this server.
	// You can set these to '' if no dumper is available.
	$conf['servers'][0]['pg_dump_path'] = '/usr/bin/pg_dump';
	$conf['servers'][0]['pg_dumpall_path'] = '/usr/bin/pg_dumpall';
```

Thanks in advance.

**Comment by klepptor** [comment]
Hi @TheJSCode 

I haven't tried that myself, but at least with the original docker-compose.yml it won't work as the Postgres port 5432 is only exposed on 127.0.0.1:

 ports: - 127.0.0.1:5432:5432

So, for an external system to access the GL db you have to change this setting.

**Comment by TheJSCode** [comment]
@klepptor I did, but it doesn't seem to work.

**Comment by TheJSCode** [comment]
I changed it to the local IP address, now it still instantly rejects the connection.

**Comment by klepptor** [comment]
Hm, should simply work then...

Did you try another external port? Just found some other discussion on stackoverflow about this.

And you don't use a firewall like ufw or sth? Sorry...

**Comment by TheJSCode** [comment]
No, I don't.

**Comment by TheJSCode** [comment]
Can you link me the discussion on stackoverflow?

**Comment by klepptor** [comment]
Argh, of course I can't find it again... 

Maybe this one: https://stackoverflow.com/questions/30770898/cannot-connect-to-postgres-server-in-docker

Maybe it's because of settings in /var/lib/postgresql/data/pg_hba.conf

=============
'# TYPE  DATABASE        USER            ADDRESS                 METHOD

'#  "local" is for Unix domain socket connections only
local   all             all                                     trust
'# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
'#  IPv6 local connections:
host    all             all             ::1/128                 trust
 '# Allow replication connections from localhost, by a user with the
 '# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

host all all all md5
=============

**Comment by TheJSCode** [comment]
The folder "/var/lib/postgresql/data" doesn't exist on my server.

**Comment by TheJSCode** [comment]
@klepptor After a check, I found out that the port :5432 seems closed. What can I do?

**Comment by klepptor** [comment]
The path is from inside the Postgres container. You could map your own pg_hba.conf via docker volume and change 127.0.0.1 to 0.0.0.0 and try if that works.

I don't have a test vm right now to check.

**Comment by TheJSCode** [comment]
It doesn't work. I still get a "login failed" message.

**Comment by klepptor** [comment]
Hm, sorry then.

 Maybe you should head over to  forums.docker.com as I really don't think it's a Greenlight problem.
