### ISSUE TITLE
statistics for records

### ISSUE THREAD

**Issue by kinimodmeyer** [bigbluebutton/greenlight#273]
hello together,

would be great if there would at least a column on the records page where you can see how often a record was played backed.

**Comment by jfederico** [comment]
This requested feature may look easy, bit it is actually not.

Can you elaborate on the use case for this? Why do you need this feature?

There may be two ways to accomplish this. 
- On Greenlight, tracking the clicks on the recording, but it is not really accurate because it would be counting clicks no views.
- On BigBlueButton, but this would be the hard way. It would be required to track the time spend in the player, a callback to update Greenlight stats and furthermore, perhaps a notification to the clients through action cable.

And after all this, now we would need to decide where to put that data as the recording can have multiple formats.

**Comment by farhatahmad** [comment]
As Jesus stated above, this is trickier then it seems. Unless BigBlueButton begins tracking the number of views on the recordings, Greenlight will not be able to accurately display this information
