### ISSUE TITLE
don't run puma as root

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/greenlight#2738]
Change the user the main process (puma) runs as to a restricted user.
containers should not run things as root ...

**Comment by farhatahmad** [comment]
Can you provide some more information on this? Possible implications? Possible fixes?

**Comment by fireba11** [comment]
Sure.
It's bad for security of your host if your container got processes running as root. On a hardened kubernetes it's simply not allowed for example. I'm not very familiar with puma but it should be fine to run it as a limted user since there is no need to bind to a port <1024 since there is an nginx as proxy in front of it anyways.

**Comment by l00ptr** [comment]
@fireba11 running greenlight with a dedicated user (and without docker) is possible. 

So i guess it could be nice to run greenlight / puma with a dedicated user even into the container.

**Comment by l00ptr** [comment]
here is a first version of a MR to implement this : https://github.com/bigbluebutton/greenlight/pull/2868

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
