### ISSUE TITLE
LDAP Fallback Server

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2740]
It is possible to set an .env variable for a fallback LDAP Server?
I think it is useful for the future releases

**Comment by einhirn** [comment]
We just used "ucarp" to enable a virtual IP that fails over to the other ldap server in case the first goes down. We added a rudimentary check via cron to force a takeover should the server be up but ldap down...

Other languages have that kind of feature, where you can add multiple LDAP servers, so that after the connection to the first one times out it tries the second etc. but for Ruby this seems to be a long way gone. It's mentioned in https://github.com/ruby-ldap/ruby-net-ldap/issues/246, but that one doesn't seem to be implemented yet. Also they asked for it to be a separate issue - don't know whether someone opened that one.
