### ISSUE TITLE
edit register form greenlight

### ISSUE THREAD

**Issue by mhkjoon** [bigbluebutton/greenlight#2776]
hi 
I need to change the registration form and get the phone number from the student, how can I add it?

**Comment by farhatahmad** [comment]
You'll need to know some basic Rails in order to get that done. Here's a list of things you need to do:
- Create a migration that adds a phone number column to the users table
- Add an input field to the registration form
- Extend the controller to allow for the new parameter 
- update the profile page to allow users to edit their info
