### ISSUE TITLE
Upload Multiple Presentations Per Room

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/greenlight#2811]
Hello,

**Feature Request**: [_Upload Multiple Presentations Per Room]_

Some users have been requesting the ability to upload multiple presentations within a Room -  
 / Add Presentations /
and allow the ability to set default Presentation from the list of Presentations within the Room settings.

~b10

**Comment by ReimarBauer** [comment]
We prefix the names of our presentations by the order of topics. They are also get sorted by this and the lowest number gets the default presentation. When there is a change that behaviour should be kept as option.

**Comment by ReimarBauer** [comment]
I'm not a fan of storing on many places a set of presentations. Usually someone comes last minute and wants to update. When in greenlight the presentations are stored, then the user can't usually update his presentation himself.

The API of BBB uses currently an url to 1 presentation. Additional I would prefer a configuration of a webdav source. This may be interesting not only for having a store to fetch also for sharing same presentations this is for some users already a common option.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
