### ISSUE TITLE
FR: BBB 2.4 Activity Report integration

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/greenlight#2873]
Is there any plans about BBB 2.4 Activity Reports integration to Greenlight?

It'll be very useful to see your rooms' all activity reports.
Also it will be so important to add feature for viewing Activity Reports of All Rooms for Greenlight Admins.

Thanks for great job. 
Looking forward!!

**Comment by farhatahmad** [comment]
That's definitely something we'd look forward to adding. I'll coordinate with the BigBlueButton team to make sure its accessible to the FrontEnd

**Comment by samuelpetrosyan** [comment]
It would be so good!! Thanks! Looking Forward!

**Comment by Ashrafhaq** [comment]
Waiting for this. Thanks! Looking Forward!

**Comment by HasanMajhali** [comment]
Waiting for this. Thanks! Looking Forward!

**Comment by kusznerr** [comment]
Bumping this requirement. We have a lot of queries from our clients.

**Comment by kusznerr** [comment]
> We have the data in BigBlueButton, and we want to put it into Moodle, Greenlight, and other front-ends.
> 
> This will be an area we work on in 2022.

@ffdixon, do you know where the learning-dashboard data is kept on BBB servers? I tried to look it up, no luck.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
