### ISSUE TITLE
[OpenID Connect] user roles supported?

### ISSUE THREAD

**Issue by beckerr-rzht** [bigbluebutton/greenlight#2946]
I am looking for a way to set **user roles** when authenticating via _OpenID Connect_.
Someting similar to `LDAP_ROLE_FIELD` for authentication via _LDAP_.

**Comment by beckerr-rzht** [comment]
I implemented this analogous to `LDAP_ROLE_FIELD` and opened a pull request: #2955

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
