### ISSUE TITLE
add user concent checkbox for learning dashboard

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/greenlight#2979]
Same as there is a checkbox by which users consent to be part of the recording when entering the meeting, there is a request due compliance with GDPR of adding a box for consenting to the learning dashboard.

**Comment by farhatahmad** [comment]
What's the "learning dashboard"?

**Comment by ffdixon** [comment]
See https://docs.bigbluebutton.org/2.4/new.html#learning-dashboard

**Comment by ichdasich** [comment]
In the process of this it might be nice to make the dasboard configurable from greenlight.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
