### ISSUE TITLE
Feature request: Pass nickname as part of room URL (for guests)

### ISSUE THREAD

**Issue by alesresearch** [bigbluebutton/greenlight#2983]
I would like to be able to send out room URLs which already contain the "nickname" which is displayed in the participant list: https://demo.bigbluebutton.org/b/xxx-yyy-zzz?nickname=anyname

The goal is to have a "single click" access to the room, so that whoever receives the url can skip the passage where they have to write their name, and can directly access the room. This system would be useful in mass-mailing systems where we want to involve tens or hundreds of users, without requiring them to register, but keeping track of who actually participates, avoiding that they use fancy names.

**Comment by jfederico** [comment]
This is a dangerous feature we need to discuss a little more. We in fact recommend to only allow authenticated users into the meetings as that anonymous join could lead to a number of issues in closed or private meetings.

One way to overcome the risks could be to generate the invitations from GL itself and include a unique token in the URL. But still would have to be discussed.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
