### ISSUE TITLE
Error 502 after fresh installation if postgres-password contains a slash /

### ISSUE THREAD

**Issue by talpaworld** [bigbluebutton/greenlight#2988]
It looks like the postgres-password generated for docker-compose.yml will not be transferred to .env if it contains a slash (/).
Greenlight then starts with an error 502.

**Comment by jfederico** [comment]
So the issue is with your deployment. Because bbb-install generates a `openssl rand -base64 24` see https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L772

Neither running from source and defaults nor installing with bbb-install will cause that problem.

If you have your own password on an existing database, I presume you edited your docker-compose, so you could enclose the string with "" in docker-compose. But the safer would be for you to change the password or create user specifically for this application/deployment
