### ISSUE TITLE
docker-compose.yaml file needs to be tuned up

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/greenlight#2992]
There are several issues with the docker-compose file that limit the possibilities for the deployment. In fact is not very helpful in the way it is.

- env variables should be passed to docker compose
- we should get rid of the option for sqlite as we are not shipping it anymore
- we must remove the 127.0.0.1 from the port
- remove the alternate settings for external logs and add journald driver (which is what BBB uses anyways)

Additionally, we can include a docker-compose-all-in-one.yaml file  for cases when gl is executed outside BBB, 
- that should include nginx for reverse proxy
- that should also include configuration for certificates

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
