### ISSUE TITLE
As an admadministrator I should be able to create rooms for other users

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#3028]
As a school administrator I should be able to create rooms for my teachers, without using the share feature.

**Comment by KH-Amir-TN** [comment]
Hi @GhaziTriki,
It appears that at the moment there's no direct way for an admin to create a user account or a room and assign it to a specific user from their admin panel.
But, an administrator can make this workaround:

1. Register a temporary user account.
2. Create and configure its rooms.
3. Merge the temporary account with a specific user which will result in merging all of its rooms accordingly with a prefix **(Merged)** added to their respective name (including the temporary account home room).

I agree with you on that, an administrator should manage the whole platform from its admin panel including creating users and managing their rooms.
Therefore, I'll proceed in labeling this issue as a **feature request**.
I'll add @farhatahmad to this conversation to see his opinion either.

Amir,

**Comment by ranjithrajv** [comment]
> It appears that at the moment there's no direct way for an admin to create a user account or a room and assign it to a specific user from their admin panel.

I think this can be solved by developing a feature for admin to impersonate the user. This is a standard practice is many projects.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
