### ISSUE TITLE
Creation of rooms limit

### ISSUE THREAD

**Issue by phillwuk** [bigbluebutton/greenlight#3029]
As the current default, there are only 2 ranks... User and Admin. Whilst you can set the maximum number of rooms a 'User' can create, any other rank is also limited by this number. This is not satisfactory for additional ranks such as Presenter who need the ability to create an unlimited number of rooms the same as the rank of Admin can and use the permissions in the current system to set what they can and cannot do on the system unencumbered by the room creation limit.

The change suggested can be achieved by altering 

'return false if current_user&.has_role?(:admin) || limit == 15' to 'return false if !current_user&.has_role?(:user) || limit == 15' in the files 
https://github.com/bigbluebutton/greenlight/blob/master/app/helpers/rooms_helper.rb#L35
and 
https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/rooms_controller.rb#L425

This does mean recompiling each time a version change is made instead as well as the initial instance.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by lonesomewalker** [comment]
Well, now in Greenlight 3, there is a hardcoded limit of 100 rooms.
Not configureable, bad design.
