### ISSUE TITLE
playback 500 Internal Server Error after upgrade 2.2 to 2.4

### ISSUE THREAD

**Issue by mhajim** [bigbluebutton/greenlight#3053]
Hi,
I have installed new BBB (2.4) and move my greenlight backup(DB+recorded files) from old BBB(2.2) and it works but the problem is recorded videos!!

I got this error:
500 Internal Server Error

URL: https://my-domain.com/playback/presentation/2.3/b62490c260a8eac2d9df5b8b68f20db0828616c7-1641002799791
Old Greenlight. release-2.9.2
New Greenlight. release-2.10.0.3

/var/log/nginx/error.log:
*6415 rewrite or internal redirection cycle while internally redirecting to "/playback/presentation/2.3/index.html", client: 1.1.1.1!, server: my-domain.com, request: "GET /playback/presentation/2.3/b62490c260a8eac2d9df5b8b68f20db0828616c7-1641002799791 HTTP/2.0", host: "my-domain.com", referrer: "https://my-domain.com/b/admins/recordings"

I run bbb-record --rebuildall but still have an error!

**Comment by ffdixon** [comment]
Can you do a new recording -- does that work?  What is the output of `ls -al /var/bigbluebutton/playback/presentation/
`?

**Comment by mhajim** [comment]
No, new recordings also have the same error!

```
ls -al /var/bigbluebutton/playback/presentation/ 
total 20
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Apr 20  2020 .
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Apr 20  2020 ..
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Sep  3  2020 0.81
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Sep  3  2020 0.9.0
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Sep  3  2020 2.0
```

**Comment by ffdixon** [comment]
Your 2.4 server is missing the `2.3` directory.  Here's what it looks like on one of our servers

~~~
/var/bigbluebutton/playback/presentation# ls -al
total 24
drwxr-xr-x 6 bigbluebutton bigbluebutton 4096 Dec  4 18:22 .
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Dec  4 18:22 ..
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Dec  4 18:22 0.81
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Dec  4 18:22 0.9.0
drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Dec  4 18:22 2.0
drwxr-xr-x 4 bigbluebutton bigbluebutton 4096 Dec  4 18:22 2.3
~~~

(The recording format for presentation has not changed from  2.3  to  2.4  which is why you don't see a `2.4` directory.)

Can you try running

~~~
sudo apt-get --reinstall install bbb-playback
~~~

on your 2.4 server and let us know if you now see the playback.

**Comment by mhajim** [comment]
TNX,
It works Like a Charm.
