### ISSUE TITLE
Link users logged in with omniauth to existing local users

### ISSUE THREAD

**Issue by cherbst** [bigbluebutton/greenlight#3076]
We'd like to add OpenID connect authentication to our Greenlight instance while being able to keep the locally created users. For now if a user logs in with OpenID connect with an existing E-Mail address a new user is created. We would like to link the OpenID Connect account to the existing Greenlight account instead like it is possible in Gitlab e.g. : https://docs.gitlab.com/ee/integration/omniauth.html#link-existing-users-to-omniauth-users

We would also consider creating a PR if someone could point us in the right direction to were to implement this feature.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
