### ISSUE TITLE
Error when adding a user on command line ('Invalid Arguments')

### ISSUE THREAD

**Issue by DecaTec** [bigbluebutton/greenlight#3089]
I've installed Greenlight with the [bbb-install script](https://github.com/bigbluebutton/bbb-install) (parameter `-g`).
This works like charm, but when adding the first user as admin on the command line
```
docker exec greenlight-v2 bundle exec rake user:create["Admin","my@email.com","!mYsuPerPassw0rD$","admin"]
```
I get the following error:
```
Invalid Arguments
{:password=>["is invalid"]}
```

Installing Greenlight manually (from the [BBB docs](https://docs.bigbluebutton.org/greenlight/gl-install.html)) makes no difference.

The only way to get this done is:
* Installing Greenlight v2.10.0.3 (downgrade)
* Add the user with the command shown above
* Updating Greenlight to latest version

I've seen the changelog for v2.11.1

> Changed default admin password to match new complexity requirements

But the password given had a high complexity (numbers, digits (upper and lower case), special characters), so I don't think that this is the problem here.
However, even if the complexity requirements are not met, the message "password is invalid" seems to be a bit odd.

Am I missing something?

**Comment by KH-Amir-TN** [comment]
Hi @DecaTec 

As of the latest release **Greenlight** now have a password complexity that every user with a local account must respect.
The password complexity is the fallowing:
1. A password should have at least **One digit**.
2. A password should have at least **One symbol**.
3. A password should have at  least **One Upper case letter**.
4. A password should have at least **One lower case letter**.
5. A password should be at least **8 characters in length**.

The password `!mYsuPerPassw0rD$` is indeed valid.
I have run `docker exec greenlight-v2 bundle exec rake user:create["Admin","my@email.com",'!mYsuPerPassw0rD$',"admin"]` on the latest docker image `bigbluebutton/greenlight:v2` `bigbluebutton/greenlight@sha256:b7a38927ae7d71c24b9b1a439eb818400fe4cb458b17930c6815d6f3b1df9bcf` and the admin account got created successfully.
My shell was `bash` and it had some troubles inferring what is written as the password since it's inside a double quotes which cause it to get interpolated that may be the cause of the issue since you are not sending as a password what you are observing.
Kindly try writing the same password using single quotes.
As for the message **password is invalid** it's already being targeted in #3105.

Hope that helps.

Regards,
Amir,

**Comment by DecaTec** [comment]
Thanks for the explanation. Indeed, I've tried it with some other passwords and then it worked. Was a password complexity issue I think. Just the error message was misleading.
But if this is already addressed in another issue, I'll close this one.

**Comment by relecand** [comment]
See here: https://github.com/bigbluebutton/greenlight/commit/e356c97ed3726037b58537a524201e2d712a190c#diff-cd92206deb936a96a1f675797e9a0a3c8d45eb267dd10ef06ddf5c1b5476d65bR51-R56
