### ISSUE TITLE
the new password rules do not match the actual pattern

### ISSUE THREAD

**Issue by rottaran** [bigbluebutton/greenlight#3091]
The validation pattern is defined here:
https://github.com/bigbluebutton/greenlight/blob/964d74689d31c98881e8fd59d9124e2c72a19d0e/app/models/user.rb#L48

The password change formular says:
* At least 8 characters
* At least 1 lowercase character
* At least 1 uppercase character
* At least 1 number
* At least 1 symbol

https://github.com/bigbluebutton/greenlight/blob/964d74689d31c98881e8fd59d9124e2c72a19d0e/app/views/users/components/_password_security.html.erb#L27

Some users have tried to use `,` and `.` as symbol. This is not in the pattern `#?!@$%^&*-`. There are likely other symbols that users will come up with.

It might be wise to explicitly state the available symbols on the user interface or accept anything other than digits and a-zA-Z as symbol.

**Comment by falkiy** [comment]
Hi, struggled and wondered today creating new users.

`root@server:~# docker exec greenlight-v2 bundle exec rake user:create["test","test3@test.de","$(pwgen 8 -scy)","admin"]
Invalid Arguments
{:password=>["is invalid"]}`

`root@server:~# docker exec greenlight-v2 bundle exec rake user:create["test","test3@test.de","$(pwgen 8 -scy)","admin"]
Invalid Arguments
{:password=>["is too short", "is invalid"]}`

`root@server:~# docker exec greenlight-v2 bundle exec rake user:create["test","test3@test.de","$(pwgen 8 -scy)","admin"]
Invalid Arguments
{:password=>["is invalid"]}`

`root@server:~# docker exec greenlight-v2 bundle exec rake user:create["test","test3@test.de","$(pwgen 8 -scy)","admin"]
Account successfully created.
Email: test3@test.de
Password: M6~Yq~O?
Role: admin`

Seems not very stable. No problem for me deploying manual and finding this issue, but maybe real issue in scripted environments (ansible and so on)?

thx && greets

**Comment by lonesomewalker** [comment]
Yeah, you are absolutely right, it was a nightmare :-/

**Comment by Hamid-Najafi** [comment]
same problem :(
Invalid Arguments
{:password=>["is invalid"]}

**Comment by KH-Amir-TN** [comment]
Hi **everyone**,

After reading carefully all of your comments I want to ensure you that all of the issues that was caused by the latest release are under our radar and has the highest priority.
We do apologize if you had any bad experience of any sort using Greenlight. 
Be sure that our goal is to provide the best to our community and it's only a matter of time to come back on this and see what should get improved or even redesigned so that it best answers our community expectations like always.

**Amir,**
**Regards,**

**Comment by KH-Amir-TN** [comment]
Hi @falkiy,

A valid password that meets the minimal required complexity is:
1. A password with at least **One digit**.
2. A password with at least **One symbol** (We're working on ensuring all options are included).
3. A password with at  least **One Upper case letter**.
4. A password with at least **One lower case letter**.
5. A password with at least **8 characters in length**.

The `pwgen 8 -scy` will only ensure generating:
1. A secure (random) password.
2. Eight characters in length.
3. That includes at least one upper and one lower case letter.
4. That includes at least one symbol.
This doesn't fully respect the minimal required password complexity since it may generate passwords without any digit.

I suggest using `pwgen 8 -sync` instead in your tests.

Amir,

In addition, as described by this issue you may stumble upon passwords that include a digit but an uncaught symbol i.e. **.** or **,** etc...

**Comment by lonesomewalker** [comment]
I think, when adding users by command line, there should be NO restriction about passwords, also the complexity criteria should be an OPTION  in the backend, maybe ticked as active by default.

With this change you clearly showed NO experience in UX, since a complex password provides NOT MORE SECURITY, it gets even worse.

**Comment by falkiy** [comment]
@KH-Amir-TN 
y you don't just include any special characters found on a common qwerty keyboard? Wouldnt this improve security of passwords even more? We're often using very random passwords (something like pwgen -sy 24). Please consider, on a service point of view i have no time to figure out and explain to customer which special character is allowed and which not.
thx
