### ISSUE TITLE
how to disable the forced password changes?

### ISSUE THREAD

**Issue by rottaran** [bigbluebutton/greenlight#3092]
How can we disable the forced password change on login? The long term users do not expect that they have to set a new password and get surprised by the change form just before starting a meeting or class. That's the worst possible point in time to come up with a good password. Many are confused because their old password was matching the rules already.

**Comment by rottaran** [comment]
I solved it with `psql -U postgres greenlight` and 
```
update users set secure_password=true;
```

**Comment by KH-Amir-TN** [comment]
Hi there @rottaran 
As of the latest releases of Greenlight the `secure_password` attribute was introduced to help the application detect the complexity of the password and to make the proper actions accordingly.
The `secure_password` will default to `false` forcing users after the upgrade to reset their passwords to one that meets the minimum complexity criteria.
A database administrator could use that flag to check gain some information after the upgrade takes place i.e. How much users had changed their passwords after the upgrade etc...
You can update that attribute to be truthy for all of your users after upgrading Greenlight  (GL) to avoid forcing them to reset their passwords so that it can be checked for complexity but this will result in having old insecure passwords in use after the upgrade (it's not problematic if you don't mind that.).
All of this can be changed in future releases so I invite you to stay synchronized with the GL project upstream.
I'll proceed in closing this issue since it does introduce a question that I hope that I have answered with this comment.
The issue will remain in the GL project despite its closing so others in the community will still benefit of it.

Amir,
Regard,

**Comment by rottaran** [comment]
Dear Amir, many thanks for your reply. I agree that increasing the security is a good thing. What catched us on a cold foot was that the release notes didn't warn about this change affecting every user. 

> A database administrator could use that flag to check and gain some information after the upgrade takes place i.e. How much users had changed their passwords after the upgrade etc...

The administrator would basically just see who logged in since the update or who did not, because everybody is forced to update the password even if it was secure already according to the pattern. There was some suggestion to use the clear text password during the login process to decide on this, but I could not find that in the implementation yet. 

From a security administration point of view a date-time of the last password change seems to be more interesting than just the single true/false flag. But I have no real experience and needs there. Just my 2 cents.

**Comment by KH-Amir-TN** [comment]
You got reason on that @rottaran.
I'll see what we can do.

Amir,
