### ISSUE TITLE
Room names can't be one charcater long

### ISSUE THREAD

**Issue by worldthumbler** [bigbluebutton/greenlight#3094]
When you try to start a Room named only with one character eg. "1" or "a" you cannot start it.

from greenlight log:
ERROR: [***] Support: mar-foe-9nv-efa start failed: Meeting name must be between 2 and 256 characters, messageKey: sizeError

greenlight v2.11.1 / BBB V2.4.1

Needs Testing for BBB V2.4.2

**Comment by worldthumbler** [comment]
As expected also occuring with BBB V2.4.2

Workound: Rename room name to more than 1 character

**Comment by worldthumbler** [comment]
Could be avoided by requiring at least 2 characters when creating a room:

https://github.com/bigbluebutton/greenlight/blob/a6ce974b883927c2b5a443831dfa65cd7ad9be77/app/views/shared/modals/_create_room_modal.html.erb#L31

`              <%= f.text_field :name, id: "create-room-name", class: "form-control text-center", value: "",**minlength: 2,** placeholder: t("modal.create_room.name_placeholder"), autocomplete: :off, required: true %>
`
Problem would still be there for existing rooms

**Comment by KH-Amir-TN** [comment]
Hi there @worldthumbler,
We are aware of this issue since it was opened 11 days ago in #3073.
Since this issue address the same problem as an already opened one in the greenlight project and to keep the number of opened issues as low as possible for a better, fast and efficient maintenance.
Unfortunately,  I'll have to proceed in closing this issue in favor of #3073.
As for your pull request @farhatahmad will review it and if it fixes the issue then he will added to one of the next releases.
I personally was assigned to solve #3073 which will answer your needs so I invite you to fallow us there. 

Regards,
Amir,
