### ISSUE TITLE
Allow room level video recording visibility settings

### ISSUE THREAD

**Issue by dlkulp** [bigbluebutton/greenlight#3097]
Is there a room level setting to change the default visibility of all video recordings? Would be nice if professors could change the institution default on a per room basis.

**Comment by KH-Amir-TN** [comment]
Hi @dlkulp,

Thank you for pointing out this.
We'll soon check it out.

Regards,
Amir,

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
