### ISSUE TITLE
Transfer all organization settings (users, rooms, room settings, site settings, roles) 

### ISSUE THREAD

**Issue by gonza-bel** [bigbluebutton/greenlight#3099]
Hello. There is a task. It is necessary to transfer all organization settings (users, rooms, room settings, site settings, roles) from bbb version 2.3 to version 2.4 (there is already a server with version 2.4). How to do it? Nowhere is there any instructions on how to transfer settings.

**Comment by gonza-bel** [comment]
Perhaps it is worth introducing buttons with saving and importing settings into the greenlight interface?

**Comment by KH-Amir-TN** [comment]
Hi @gonza-bel,

I believe you are asking on how to upgrade an existing deployment from **v2.3** to **v2.4**.
If that's the case then most of Greenlight settings should be in the `.env` and `database` files.
Kindly check the **v2.4** changelog [click here](https://github.com/bigbluebutton/greenlight/releases/tag/release-2.4) to see what changes.
If the deployment you have isn't customized it should be safe to get upgraded.
You'll have to stop the running image (Note that this will stop your application and prevent users from accessing it) and run the newer one instead (I recommend that you pull the image before stopping the running application for a faster transition [click here](https://hub.docker.com/r/bigbluebutton/greenlight/tags?page=1&name=2.4). ), Greenlight will then upgrade the schema of the existing database to match the new changes accordingly by running any new detected migrations.
If it's not mentioned otherwise in the changelog the upgrade should be safe to run on existing deployments.

If you'll use a new server to host the application with the newer version then you can simply either:
1. Manually export the database in use and import it in the new server **database** (There's a lot of ways to do this, I recommend that you fallow our guidelines for backing up your database [here](https://docs.bigbluebutton.org/greenlight/gl-config.html#create-a-backup-of-your-database).).
2. Configure the new server to use your old database by changing the settings in its `.env` file [click here](https://github.com/bigbluebutton/greenlight/blob/release-2.4.2/sample.env#L211) (but that means you'll have two server running one for **Greenlight v2.4** and one for the **database**).

Since, this not an issue but more of a question I'll proceed in closing it for a better visibility of other issues in the project.
I kindly invite you to reopen if you feel otherwise.
Despite the state of the issue you can still comment and I'll be here to make sure that you have successfully upgraded your system.
I kindly invite you in case you have other questions that you believe cannot be considered as issues to post it in **BigBlueButton Greenlight** community support group [click here](https://bigbluebutton.org/community-support/).

Hope this helps.

Regards,
Amir,

**Comment by KH-Amir-TN** [comment]
> Perhaps it is worth introducing buttons with saving and importing settings into the greenlight interface?

IMHO I believe this is more of an operational administrative task more then a feature that can have great added value to the project.
Greenlight settings just like any other application are stored in its database mainly and the state of the application can be reset, reverted, backed up by using the database system utilities.
I've left some steps to guide you to achieve that in the comment above. 

Sincerely,
Amir,
