### ISSUE TITLE
External logotype inclusion

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/greenlight#3104]
Hello,
I believe that external inclusion of logotype from github should not be made even as default feature. 
It that for spying after your users?

![002](https://user-images.githubusercontent.com/1878503/151706134-c5d20da6-6f2f-419e-9877-8b50c2292ace.png)

**Comment by KH-Amir-TN** [comment]
Hi @greenycat,

Could you please explain what do you mean by **It that for spying after your users?**?
Could you also provide reasoning behind your suggestion that we **shouldn't be using the logo from GitHub by default**?

Sincerely,
Amir,

**Comment by greenycat** [comment]
> 

Hello.
I have some considerations that this has to be a local file (which is already bundled in package, just url to be changed).

1. Server may be running within network that has no access to internet (obscures interface, shows spinner on tabs if network is too limited).
2. The policy of requests to external sources as far as I know should explicitly accepted by end user.
3. Logfiles on githubusercontent are disclosing all installations and this is security issue for 0day, for yet unknow, hypotetic vulnerabilities for those who has access to such log files.

**Comment by KH-Amir-TN** [comment]
Hi @greenycat,

>1. Server may be running within network that has no access to internet (obscures interface, shows spinner on tabs if network is too limited).

We'll take this into consideration, I've tried running Greenlight myself with no internet access and only the logo didn't appear I couldn't confirm the spinner that you are mentioning but I agree with you on this.
>2. The policy of requests to external sources as far as I know should explicitly accepted by end user.

Accessing icons, logos and/or pictures or any resource AFAIK isn't illegal if the object use isn't subject to ownership/licensing violation and since **Greenlight** is a project under the **BigBlueButton** trademark this IMHO shouldn't be an issue.
Accessing external content may be problematic and requires end users acceptance but accessing icons, logos and/or pictures with relevance to the application in use without violating any ownership doesn't set under the same umbrella, please feel free to correct me If I'm missing something.
I kindly invite you to share any law or regulation that you believe it's not being respected in here.

>3. Logfiles on githubusercontent are disclosing all installations and this is security issue for 0day, for yet unknow, hypotetic vulnerabilities for those who has access to such log files.

Could you further explain this point?
Greenlight isn't sharing any log files with the upstream even for forked repositories kindly check the `.gitignore` [FILE](https://github.com/bigbluebutton/greenlight/blob/master/.gitignore#L27) entries.
