### ISSUE TITLE
Feature Request : Scheduled Meetings

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/greenlight#3125]
**Is your feature request related to a problem? Please describe.**
There is no option to communicate to the audience about scheduled time or other details of the upcoming meeting. Current versions only allow to communicate that 'the meeting hasn't started yet'.

**Describe the solution you'd like**
Make the guests wait in guests lobby until the scheduled time, open the room at scheduled time and allow guests in.

**Describe alternatives you've considered**
Couldn't find any alternatives.

**Additional context**
I think this feature will be complimentary to already listed features for v2.5 'Improvements to Guest Lobby: Private guest lobby message, display of waiting time, moving users back to the lobby, display position in waiting line'.

Creating an issue here based on suggestion here https://github.com/bigbluebutton/bigbluebutton/issues/14326#issuecomment-1034919962_

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
