### ISSUE TITLE
Wrong password requirments

### ISSUE THREAD

**Issue by lupa18** [bigbluebutton/greenlight#3150]
Hi ! I'm using [this BBB](https://ourvoices.live/b) instance and it supposed it has a new password requirements control (Maybe related to #1103 ?)

The issue is: when do a login, BBB ask me to change the password to "more complex one". So I created one or two, meeting the requirements, but it says: "Password did not meet complexity requirements".

One example that fails is: "Elephant..4444  blue" (more than 8 chars, lowercase, uppercase, numbers, and symbols: 2 points and 2 spaces).

Then, I tried other symbols than "." and " " and worked. 

But I think it's an error from users point of view. It should be fixed or at least an advice should be added, "Symbols not allowed are: .... "

thanks in advance!

**Comment by scouillard** [comment]
Hello,

I was able to create a user with the suggested password "Elephant..4444 blue".

This was fixed in the [latest version](https://github.com/bigbluebutton/greenlight/releases/tag/release-2.11.2)

Please confirm what Greenlight version you are using.

If you are using Greenlight via a docker image, you can follow the updating guide [here](https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight)

**Comment by lupa18** [comment]
Not sure bc I'm only an user. But I'm going to close and if persists I can ask version and open again if necessary.
