### ISSUE TITLE
support multiple endpoints / integrate load-balancer

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/greenlight#3261]
By integrating the load balancing functionality into Greenlight, some nice things would become possible:
* allow to manually assign a Greenlight room to a BigBlueButton server to e.g.
  * choose jurisdiction (and physical location) where you host the meeting
  * choose a server with more resources to host big sessions
  * host meetings on different servers depending on what a client pays for and what configuration they wish to have
* Greenlight has more information to make smart load-balancing decisions (how many users have access to this room, how big/long were the last meetings in this room,..)
* easier installation and configuration

**Comment by lonesomewalker** [comment]
As much as i agree, this makes Greenlight much more complex.
And with an eye to the current PR situation, i don't expect this in the near future :D

**Comment by hex-m** [comment]
From a recent [post](https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo/m/Nv4eGv3YAQAJ) on the bigbluebutton-dev mailing list:

> we have decided to do a full rewrite once again [..] we have assembled a full team of Developers that work for Blindside Networks, who will be focused full-time on Greenlight during the next few months.

> don't be surprised for the number issues and PRs are opened during the days ahead :)

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by hex-m** [comment]
This feature request is directed towards Greenlight v3. The idea is to invite the core team to think about this early in the development of v3.
