### ISSUE TITLE
Configurable password complexity

### ISSUE THREAD

**Issue by Joa-Hoffmann** [bigbluebutton/greenlight#3268]
Hello, 

is there a possibility to configure the password complexity?
This would be a great point to adapt to some company guidelines. 

KR, Jo

**Comment by scouillard** [comment]
Hi Jo,

There is currently no user interface to change the User password complexity.

However, you can change the password validation (format, length, confirmation) in the User model @ app/models/user.rb

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by Joa-Hoffmann** [comment]
> Hi Jo,
> 
> There is currently no user interface to change the User password complexity.
> 
> However, you can change the password validation (format, length, confirmation) in the User model @ app/models/user.rb

Ok, thx. I'll give it a try.

**Comment by Joa-Hoffmann** [comment]
> Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3! If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.
> 
> To find out more information on Greenlight v3, please click the following link: https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo
> 
> Thanks for your continued support!

Ok, thank you. I'll try the hint above and if there is still a need to get it in an easier-to-configure way, I'll re-create the issue.
