### ISSUE TITLE
Problem in RECORDING page

### ISSUE THREAD

**Issue by alizamanir** [bigbluebutton/greenlight#3307]
Hello
After updating to 2.12.1, I can see the recordings for every room,
but when I go to recording page, it says: 
Server Error
Invalid BigBlueButton Endpoint and Secret

all data in .env are correct and I can create rooms and enter them, the issue is just for RECORDING page.

the error log in the ~greenlight/log/production.log have nothing about this error.

have you any suggestion for this issue?

Thanks

**Comment by KH-Amir-TN** [comment]
Hi @alizamanir ,

I have tried reproducing your case but I couldn't confirm it.
So, could you please confirm that:
1. You are using an official image.
2. You have fallowed our recommendations  to deploy and configure your instance.
3. You have faced this issue after upgrading an existed and working instance.
4. Greenlight application works as expected except for the issue that you described, any other things to add/ to note?
5. When entering a room could you confirm that:
5.1 The recordings are displayed in the **Room Recordings** table correctly?
5.2 Selecting a recording and changing its visibility and name, removing and presenting it all works as expected?
In case something goes wrong please specify exactly which feature didn't work while providing as with any helpful information (logs, screenshots...).
6. When entering the **All Recordings** page, could you confirm the same points described in `5)`.

For the mean time, I'll have to temporarily close your issue for a better visibility on our side since we are working on the development of [Greenlight v3](https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo/m/Nv4eGv3YAQA).
_This doesn't mean that we will not help you resolve your issue._

Regards,

Amir,

**Comment by alizamanir** [comment]
Hello

1-Im using the latest official version of Greenlight (release-2.12.1 )
2- Yes, I did, I have more then 20 active Greenlight on different servers
3- this error was not reported by my client before upgrade but I'm not sure if this is an old issue or not
4-It works fine and its only problem is in RECORDINGS page
5.1 yes, it dose
5.2 yes, it dose
6- the All Recordings page opens with an error and no recording displays there, and its why opened this thread.


Thanks

**Comment by KH-Amir-TN** [comment]
Hi @alizamanir 
Thanks for your responses, it helps us a lot to deliver the best support we could.

As for your issue and after reading carefully your answers for the points that I asked , unfortunately I couldn't reproduce your case.
I have tested it on the official docker image  with the fallowing digest `bigbluebutton/greenlight@sha256:3ea1be97a5162f23d84a19fe5c8160b230d32ef140b22c9bf7ac0d67cd8d8120` for the latest relase `2.12.1.1` and I've successfully managed to record several meet session along with full accessibility to recordings on Greenlight 2.12.1.1 wither in one room scope or for `ALL RECORDINGS`.

I recommend that you share with us the production logs for when the incident occur so that we can help you solving it.
For us now this cannot be considered as an issue for the **Greenlight** project.

Regards,
Amir,

**Comment by alizamanir** [comment]
Thanks for your response.
this issue is not applyed on new installations, and I had not such error before updating the Greenlight.
After update, I get error on "All Recordings" page and I see no log on production.log for this.
I deleted all entries on this file (~/greenlight/log/production.log) and re-produced the error by clicking on "All Recording" page, I get the error on web page as follow, but there were no error log in the production.log

------------------------------------------
Server Error
Invalid BigBlueButton Endpoint and Secret

Please make sure the proper steps have been taken. [Learn more](https://docs.bigbluebutton.org/greenlight/gl-install.html#setting-bigbluebutton-credentials) 
------------------------------------------

As I told before, the Endpoint and Secret are correctly entered in the .env file and all parts of the greenlight are working properly except of "all recordings"

is there any other LOG file for to check for this issue?

Thanks

**Comment by KH-Amir-TN** [comment]
Hi @farhatahmad ,
Could you give this a look?
I've tried reproducing this case twice and haven't succeeded.
