### ISSUE TITLE
BigBlueButton with Greenlight not present transferred recordings.

### ISSUE THREAD

**Issue by sara2nd** [bigbluebutton/greenlight#3662]
**Describe the bug**
BigBlueButton with greenlight installed by official bbb-install-2.5.sh script. After that I try to transfer recordings from old ver. 2.3 BigBlueButton follow official instructions. But no any of these records available in Greenlite admin interface.

**To Reproduce**
1. Install BigBlueButton with Greenlite v.2.6 on Ubuntu 20.04.
2. Copy records follow instructions:
https://docs.bigbluebutton.org/admin/customize.html#transfer-recordings
or
https://docs.bigbluebutton.org/admin/customize.html#transfer-published-recordings-from-another-server
3. Open admin Greenlite interface.
4. Go to Administrator -> Organization -> Server Recordings

**Expected behavior**
Transferred recordings must be on the recording list.

**Actual behavior**
No transferred recordings on the recording list.

**Additional context**
After executing instructions from:
https://docs.bigbluebutton.org/admin/customize.html#transfer-recordings
or
https://docs.bigbluebutton.org/admin/customize.html#transfer-published-recordings-from-another-server
there is no new records at list:
bbb-record --list

If old raw recordings was copied and reprocessed by: 
bbb-record --rebuild <internal meetingID> 
it showed at list:
bbb-record --list
But it not showed at Greenlight interface.

**Comment by mk-hs** [comment]
Just to make sure, did you migrate your old Greenlight database as well?

**Comment by sara2nd** [comment]
> Just to make sure, did you migrate your old Greenlight database as well?

No. I can't do db migration. The db lost with old hdd.

**Comment by mk-hs** [comment]
Your recordings should be present on your server, you can test that by sending a getRecordings call to the API.  This tool can help you with that, just enter your info, make sure "meeting id" and "recording id" is empty and click on getRecordings: https://mconf.github.io/api-mate/
The recordings should also be accessible with the same url you used on your old server right away.

However, Greenlight can only 'see' recordings, which are associated with an account/room. This basically allows multiple Frontends to use the same BBB-Server, while keeping the recordings separate, so what you're describing isn't really a bug.

To make your recordings show up in Greenlight once again, you'll have to change the `externalID `and `meetingID `within the recordings' metadata.

The metadata is here:
`/var/bigbluebutton/published/presentation/*/metadata.xml`

You can just create a new recording and analyse the new recording's metadata to find out what you need.

Otherwise, you can find it here:
```
docker exec -it greenlight-v2 bundle exec rails c
Room.find_by(uid: "ROOM_UID").bbb_id
```

The ROOM_UID is part of the room url, like abc-def-ghi-jkl

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
