### ISSUE TITLE
V3: Migrate room settings, presentations, etc

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4085]
**Describe the bug**
https://docs.bigbluebutton.org/greenlight_v3/gl3-migration.html states that "Rooms settings, presentations and shared access will not propagate from v2 to v3, so migrated rooms will have v3 the default configurations assigned."

**Expected behavior**
A migration should migrate data from one system to another as good as possible. If features between versions do not match perfectly, the migration should derive/guess information.

I as well as our users would not expect data loss if we update a software.

**Actual behavior**
It only migrates a subset of the original data.

**Comment by farhatahmad** [comment]
Due to the differences in the the data structures, moving over shared access and presentation is very difficult. Room settings are also tricky because there are some changed and some new settings, so guessing which value they would want isn't really something we want to do.

During the community calls that were done during v3, the majority of those attending were okay with resetting their room settings

**Comment by farhatahmad** [comment]
Thanks for the feedback - we'll attempt to tackle this before heading to production
