### ISSUE TITLE
V3: Establish a state ready for beta testing

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4165]
On the last community call, Fred asked us to beta test Greenlight 3. But to be honest, this application does not feel like it is in a Beta state. If I noticed correctly, quite a few other admins from the german BBB matrix channel experienced similar issues and hesitate to test it.

* There is a separate https://github.com/bigbluebutton/greenlight-run repository. I've never seen something like this. IMHO this should just be integrated into https://github.com/bigbluebutton/greenlight 
* The `bin/start` seems to create a database, but does not load the schema? https://github.com/bigbluebutton/greenlight/issues/4163
* After injecting the schema, another error occured to me: https://github.com/bigbluebutton/greenlight/issues/4164
* The `README` does barely exist.
* The migration scripts are unable to migrate some boolean values https://github.com/bigbluebutton/greenlight/issues/4085

Maybe it's possible to test it again internally at blindsight networks with somebody who never used Greenlight 3 before? This way, a reliable README could be created and "works on my dev machine" could be circumvented.

See also https://github.com/bigbluebutton/greenlight-run/issues/8

**Comment by farhatahmad** [comment]
Hi Marc,

Thank you for the detailed feedback. 

> But to be honest, this application does not feel like it is in a Beta state.

I guess this would depend on your understanding of `beta`. We perhaps should have done a better job at explaining what our goal with this release was. The `beta` release was a way for us to provide you guys with an idea of what we were up to. I would argue that this is infact a beta, but you may have run into problems since you decided not to follow our recommended method of installing. We still plan on doing a few more updates to this beta and ask that you continue to test it and provide any feedback you have

> There is a separate https://github.com/bigbluebutton/greenlight-run repository. I've never seen something like this. IMHO this should just be integrated into https://github.com/bigbluebutton/greenlight

This is based on our experience with Greenlight v2 and Scalelite. Greenlight is deployed in a million different ways to suit each organization's use case. We've opted for something like `greenlight-run` to help solve a lot of the problems we ran into when maintaing v2. Think of it almost like the `bbb-install` script - just a set of instructions and scripts to get you up and running. Ultimately, those that are "true" system admins will likely ignore any instructions and install it in a way that works with their systems (which is expected).

> The README does barely exist.

This is something we're currently working on
