### ISSUE TITLE
[v3] Unable to upload presentations larger than 1Mb/10Mb

### ISSUE THREAD

**Issue by germeier** [bigbluebutton/greenlight#5142]
I updated my BigBlueButton 2.5 to 2.6 with:
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s $SERVER -e $EMAIL -g -w`

The startpage reports `Greenlight release-3.0.3.1`

I am unable to upload presentations larger than 1Mb:
File large than 1Mb: error "The file can't be uploaded."
File large than 10Mb: error "The file size is too large."

I attached my **/usr/share/bigbluebutton/nginx/greenlight-v3.nginx**
[greenlight-v3.nginx.txt](https://github.com/bigbluebutton/greenlight/files/11241906/greenlight-v3.nginx.txt)

As I found a line `client_max_body_size 30m;` I assumed that I am able to upload file sizes of up to 30Mb, but that is not the case.

I added `client_max_body_size 200m;` to the server sections of **/etc/nginx/sites-enabled/bigbluebutton**. After that I am able to upload files up to 10Mb, but larger files still give me the message "The file size is too large."

**Comment by scouillard** [comment]
Hi,

There is a file size limitation on both NGINX and Greenlight.

For Greenlight, you can find `PRESENTATION_MAX_FILE_SIZE` in `app/javascript/helpers/FileValidationHelper`

**Comment by KH-Amir-TN** [comment]
Hi @germeier ,
Thanks for sharing a good context and providing useful steps to replicate your case.

I suspect that you're running both of Greenlight v2 and v3 on the same system.
**We do not encourage that as it will cause _issues_.**
The active storage on v3 will remain broken in other terms pre-upload presentation and upload avatar will not work because of the following LINES on `/usr/share/bigbluebutton/nginx/greenlight.nginx`:
```
location /rails/active_storage {
  return 301 /b$request_uri;
}
```

We recommend **either**:
1. Deploying Greenlight v3 on a relative URL root path other than `/` and `/b`. 
2. Removing/commenting those LINES: This will brake the pre-upload presentation feature on Greenlight v2.

If willing to deploy Greenlight 3 on the root path (the `/`) and have Greenlight v2 fully operational then we recommend setting a new clean environment dedicated for v3.

You don't have to deploy a complete BBB ecosystem for v3 since [you can use this script to deploy a standalone Greenlight v3 server](https://docs.bigbluebutton.org/greenlight/v3/install#installing-on-a-standalone-server) which can run on a minimum specs of 2/4 (CPU/RAM [GiB]) and configure it to use your BBB server (which already deployed with Greenlight v2) or re-use [bbb-instlal-2.6](https://docs.bigbluebutton.org/greenlight/v3/install#installing-alongside-a-bigbluebutton-server) on the clean system and have a completely isolated so that both versions continue to operate without clashing.

You cannot switch to Greenlight v3 because of your data?
You can follow our guides on how [to use the migration system to migrate all of your v2 resources](https://docs.bigbluebutton.org/greenlight/v3/migration).

If you're not running Greenlight v2 on the same system then please let us know,
You can always [reach us and open conversations](https://groups.google.com/g/bigbluebutton-greenlight), you'll find us there also and all of the community!

Hope that helps,
Amir,

**Comment by hostbbb** [comment]
So i have been only using bbb-install.sh for 2.6 since early betas,  it upgraded me at some point to v3.   I can not upload files >1mb and cant load jpg, and png files as a default presentation in a room.

dont have any greenlight.nginx

this is greenlight-v3.nginx### Greenlight version 3:

location /cable {
    proxy_pass http://127.0.0.1:5050;
    proxy_redirect off;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto "https";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_http_version 1.1;

    proxy_read_timeout 6h;
    proxy_send_timeout 6h;
    client_body_timeout 6h;
    send_timeout 6h;
}


location @bbb-fe {
    proxy_pass http://127.0.0.1:5050;

    proxy_read_timeout 60s;
    proxy_redirect off;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Cookie "$http_cookie; ip=$remote_addr";
    proxy_set_header X-Forwarded-Proto "https";
    proxy_http_version 1.1;

    proxy_headers_hash_max_size 512;
    proxy_headers_hash_bucket_size 128;

    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    client_max_body_size 30m;

    rewrite ~/(.*)$ /$1 break;
}

**Comment by KH-Amir-TN** [comment]
> So i have been only using bbb-install.sh for 2.6 since early betas, it upgraded me at some point to v3. I can not upload files >1mb and cant load jpg, and png files as a default presentation in a room.
> 
> dont have any greenlight.nginx
> 
> this is greenlight-v3.nginx### Greenlight version 3:
> 
> location /cable { proxy_pass http://127.0.0.1:5050; proxy_redirect off;
> 
> ```
> proxy_set_header Host $http_host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto "https";
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "Upgrade";
> proxy_http_version 1.1;
> 
> proxy_read_timeout 6h;
> proxy_send_timeout 6h;
> client_body_timeout 6h;
> send_timeout 6h;
> ```
> 
> }
> 
> location @bbb-fe { proxy_pass http://127.0.0.1:5050;
> 
> ```
> proxy_read_timeout 60s;
> proxy_redirect off;
> 
> proxy_set_header Host $http_host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header Cookie "$http_cookie; ip=$remote_addr";
> proxy_set_header X-Forwarded-Proto "https";
> proxy_http_version 1.1;
> 
> proxy_headers_hash_max_size 512;
> proxy_headers_hash_bucket_size 128;
> 
> proxy_buffer_size 128k;
> proxy_buffers 4 256k;
> proxy_busy_buffers_size 256k;
> 
> client_max_body_size 30m;
> 
> rewrite ~/(.*)$ /$1 break;
> ```
> 
> }

Hi @hostbbb 

Do you have both of Greenlight v2 and v3 installed on the same system?

**Comment by hostbbb** [comment]
https://groups.google.com/g/bigbluebutton-greenlight/c/YatCY380ij8  see this thread...

and test demo.bigbluebutton.org...    i solved the size issue by adding content size in server block,   the png/jpg not solved yet.

**Comment by germeier** [comment]
> If you're not running Greenlight v2 on the same system then please let us know,

After migrating the user data from v2 to v3 I disabled the v2 docker and the nginx configuration:

```
root@bbb ~ # ls -la /usr/share/bigbluebutton/nginx/greenlight.*
-rw-r--r-- 1 root root 1497 Apr 15 19:20 /usr/share/bigbluebutton/nginx/greenlight.nginx.disabled
root@bbb ~ # 
```
I only added a rewrite to allow old URLs to auto-magically work for the time being:

```
root@bbb ~ # grep /b /usr/share/bigbluebutton/nginx/greenlight-v3.nginx
    rewrite ^/b/(.*) https://SERVER/rooms/$1 last;

```

**Comment by hostbbb** [comment]
@germeier that file is in the greenlight docker container.  its not the issue.   see the thread above, same happens on demo.bigbluebutton.org.    adding content statement to nginx server block fixed it for me...

**Comment by germeier** [comment]
> @germeier that file is in the greenlight docker container. its not the issue. see the thread above, same happens on demo.bigbluebutton.org. adding content statement to nginx server block fixed it for me...

As I mentioned above, I already added `client_max_body_size 200M;` to the server blocks. After that I can upload files <10Mb (before <1Mb).

**Comment by germeier** [comment]
> that file is in the greenlight docker container.

I have to admit, I have no clue about docker container, so a "quick and dirty"(tm) test

```
docker exec -it greenlight-v3 /bin/bash
vi app/javascript/helpers/FileValidationHelper.jsx 
```
Change line to 
`const PRESENTATION_MAX_FILE_SIZE = 50_000_000;`

```
kill 143
```
```
root@bbb ~/greenlight-v3 # grep 200m  /usr/share/bigbluebutton/nginx/greenlight-v3.nginx
    client_max_body_size 200m;
    client_max_body_size 200m;
```
=> nginx restart

After that I am able to upload a 18Mb pdf but no 38Mb pdf. Oh, well, ... Close enough...

**Comment by jorgelondo** [comment]
Hi, I have made the changes suggested here and I have not been able to upload files larger than 1mb
Greenlight release-3.0.4
Has anyone found a solution?
