### ISSUE TITLE
Installation instructions for v3 on BBB host but with self managed BBB

### ISSUE THREAD

**Issue by toabi** [bigbluebutton/greenlight#5165]
In v2 the [installation instructions](https://docs.bigbluebutton.org/greenlight/v2/install) are clear on how to install it manually on a BBB host.

In the [v3 instructions](https://docs.bigbluebutton.org/greenlight/v3/install) there's only the option to put it on a standalone server with a dedicated script or on the bbb host using the officiall bbb-install script.

The problem with the bbb-install script is that it doesn't have an option to only install greenlight only. It does a lot of magic and tries to install/update/reconfigure the whole BBB setup (which I manage with ansible and want to keep it that way).

Or did I overlook something? What would be the best way to get greenlight v3 on a bbb-host which is not managed by the bbb-install script?

**Comment by KH-Amir-TN** [comment]
Hi @toabi,

Thanks for dedicating time to reach us and open this discussion as others might benefit from it as well.

Greenlight v3 aims for simplicity and efficiency not only to end users but also to sysadmins.

That is why we shifted our focus initially to provide dedicated scripts that can be leveraged by regular and power users.
As a result we don't currently have a step by step general purpose guide on how to install Greenlight v3.

However, the application at its core was made intentionally simple and can be managed at ease.
In fact, it will not differ a lot in management from its previous version (v2) as both applications are similar in design.

We'd be happy to provide any form of help to our community.
When having a question it's better to refer to the [community support](https://bigbluebutton.org/community-support/) for a faster response and visibility.

To confirm your case, you do have your custom Ansible playbook(s) to manage your BigBlueButton server(s) in a way that makes using the `bbb-install` script on those systems inadequate and you'd like to install and manage Greenlight v3 on those systems but without using the script to avoid missing with their configuration.

If that's the case, then initially I'd like to point out that there's no direct answer on what's the best way as there's a lot of options to consider which are driven by the setup and design of your deployment which is outside of our reach and that the rest of this answer can be considered as directions or options that might help:

- One can use the [gl-install](https://github.com/bigbluebutton/greenlight/blob/master/gl-install.sh) script to setup a dedicated server for Greenlight and configure it to use their BBB server.
One can even use [ScaleLite](https://github.com/blindsidenetworks/scalelite) so that a single Greenlight instance can make use of an entire fleet of BBB instances without having to bundle each BBB server with its own dedicated frontend.

- One can leverage the [bbb-install](https://github.com/bigbluebutton/bbb-install) script to deploy Greenlight v3 **without interacting with any of BBB components**.
How?
Greenlight management logic is part of the script but can be extracted as it's loosely coupled.
The script itself is doing nothing but calling a [function](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L403).
The function makes some [checks](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L835-L840) such as ensuring that BigBlueButton is found on the system and that docker is installed...
 Then it [prepares the environment and the configuration](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L865-L904)  for Greenlight (DB password, App secret key, BBB URL and secret, ...) which is passed to its `.env` file [as variables](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L912-L918).
 Then it places the [Nginx configuration](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L921-L922) and [installs keycloak](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L960-L997) if specified.
[Applies the configuration and (re)starts the Greenlight containers](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L1025-L1040).

The `gl-install`  and `bbb-install` scripts are open sourced so feel free to study them and create your own playbooks that best fits your needs.
You can share this with the community and benefit from their help as they benefit from your work.

To resume, a generic list of Greenlight v3 installation steps can be viewed as: 
1. Installing docker and the compose plugin.
2. Copying the `docker-compose.yml` and the `sample.env` files from the container to the host filesystem (`sample.env` must be copied as `.env`).
If willing to install Keycloak then append the `docker-compose.yml` with `docker-compose.kc.yml`.
Note: all files can be found on the official repo or the Greenlight v3 container.
3. Generate a secret password for the Postgres DB and set it to `POSTGRES_PASSWORD` in `docker-compose.yml`.
If installing Keycloak then set `KC_DB_PASSWORD` either to the **same value**.
4. Fill the [required variables](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L914-L918) in the `.env` according to the [desired configuration](https://docs.bigbluebutton.org/greenlight/v3/install#optional-env-configurations).
You'd need to:
- Generate a secret key base.
- Correctly set the database URL with the correct credentials (should be the default with the password defined in the docker-compose.yml).
- Correctly set the BBB API endpoint and secret.
- Correctly set the Redis URL with the correct credentials (should be the default).
5. If using Nginx to proxy traffic to Greenlight v3 then leverage the `greenlight-v3.nginx` preset configuration or edit it to match your deployment.
Note: By default, Greenlight is using a [named location](https://github.com/bigbluebutton/greenlight/blob/master/greenlight-v3.nginx#L22) so a `location [PATH]` that internally redirect to Greenlight is [expected](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L1453).
Note: When [deploying Greenlight v3 on a relative URL root path](https://docs.bigbluebutton.org/greenlight/v3/install#relative-url-root-path-subdirectory-setup) other than `/` the Nginx configuration has to be updated, `bbb-install` could be a [reference](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L1020-L1023).
6. Use docker compose to start Greenlight v3 containers.
If installing Keycloak then [create its database](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L960-L964) before you start it.


Hope that helps,

Amir,
