### ISSUE TITLE
Presentation error on V2.6

### ISSUE THREAD

**Issue by JohnPrice2** [bigbluebutton/greenlight#5194]
Just installed BBB 2.6, with my own certificate. Everything runs great, but when I start a new meeting this shows:

On Google Chrome:
![image](https://github.com/bigbluebutton/greenlight/assets/45044257/850b5c42-b01d-4e25-aa5a-58d71cdf6543)

On Firefox:
![image](https://github.com/bigbluebutton/greenlight/assets/45044257/b5b6c721-f8e2-4fdf-872d-d3b27d80a035)

**Comment by JeanPluzo** [comment]
Hi JohnPrice2,

this is the greenlight-issues forum, used specifically for greenlight.
Your issue seems to be regarding BBB. Please go to [this Google forum](https://groups.google.com/g/bigbluebutton-setup) and post the same issue. You will get a faster response in the Google forum than here.

Regards,
J.

**Comment by JohnPrice2** [comment]
I will, thanks @JeanPluzo.

Regards,
JP.
