### ISSUE TITLE
V2/3 Users-migration with provider change LDAP -> OpenID

### ISSUE THREAD

**Issue by Nemental** [bigbluebutton/greenlight#5305]
Hi,

first I want to provide you some basic informations about my environment.

---

**Greenlight v2**  
- Version: `2.14.8.1`
- Authentication: `LDAP` (env variables)

**Greenlight v3**  
- Version: `3.0.5.2`
- Authentication: `OpenID Connect` (env variables)

The names and email addresses of the users are matching between LDAP and OpenID provider.

---

I want to migrate all users from v2 to v3, but during the `migrations:users` there is an error:
```shell
...
Successfully migrated User:
  UID: gl-ewvkrenleysw
  Name: admin
  Provider: greenlight
Unable to migrate User:
UID: gl-mtpwkqwqbfku
Name: Testzugang
Provider: ldap
Errors: Provider does not exist

Users migration completed.
In case of an error please retry the process to resolve.
If you have not migrated your roles, kindly run 'rake migrations:roles' first and then retry.
command terminated with exit code 1
...
```

Now there is my question if it's even possible to migrate users from LDAP provider (v2) to OpenID (v3)?

**Comment by scouillard** [comment]
Hi,
This is an oversight on my part.
Working on a fix.
Thank you for the report.

**Comment by scouillard** [comment]
Fixed by #5306

**Comment by Nemental** [comment]
@scouillard 
Thanks for your quick fix! I can confirm it.  
But now it's the same with `migrations:rooms`.

**Comment by scouillard** [comment]
Hi,
Would you please upgrade to the latest version of Greenlight and see if the users can now sign in?
Thank you.

**Comment by Nemental** [comment]
Hi, thank you for your fixes 👍 The next updates and tests are scheduled for monday. I'll let you know!

**Comment by scouillard** [comment]
Glad to hear!

**Comment by parreitu** [comment]
Hi, I see that you have managed to configure keycloak to access a LDAP. I want to do the same, but I can't do it.

Once installed keycloak, I have configured "User Federation" adding a new LDAP provider. So far, no problem.

Once this is done, I understand that I need to define an Identity Provider, and I think it should be a User-Defined Identity Provider, but here I am stuck. I don't know how to do it. I have searched the github issues and the Internet in general, but I have not found it.

Since you guys have done it, could you point me somewhere where this step is documented ? or could you tell me how you have done it ?

I want to migrate Greenlight from version 2 to version 3, but I'm stuck because I can't link the new version to our LDAP.

Thank you very much !
