### ISSUE TITLE
Feature documentation

### ISSUE THREAD

**Issue by s-kucharski** [bigbluebutton/greenlight#5420]
Until now I could not find any structured feature overview and no comparison of the features of GLv2 and GLv3. Such overviews would be helpful to compare GL to other solutions and highlight the advantages of GL and the things GL is not made for.

**Comment by hex-m** [comment]
There is a [comparison-table](https://gitlab.com/bbbatscale/bbbatscale/-/blob/main/Documentation/compare-to-scalelite-greenlite.md) that compares GLv2 to BBB@Scale.

PILOS has a [similar table](https://github.com/THM-Health/PILOS/wiki/Comparison-Greenlight-and-PILOS) comparing it to GLv2.

**Comment by debuglevel** [comment]
I think such a comparison between GL2 and GL3 would need to be rather detailed: GL3 seem to be a GL2 clone to me (actually it was always announced as a rewrite) rather than a new product (which would have included a new collection of user stories, re-evaluation of existing features et cetera). Therefore they should differ only in a few added or removed features.

Nevertheless, from what I can remember testing GL3 a few months ago:

|   | GL2  | GL3  |
|---|---|---|
| Auth | internal, LDAP  | internal, Keycloak/OpenID |
| captcha  |  reCaptcha | hCaptcha  |
| under active development | no  | yes |
| access codes  | user  | user & moderation  |
| avatar  | no  | yes  |

**Comment by farhatahmad** [comment]
@debuglevel is correct here. Greenlight v3 was a re-write of v2, and not a new product. There were multiple posts and videos regarding this posted over the year that the re-write was done. Here's one that was done at the BBB World Conference: https://www.youtube.com/watch?v=WDCh9voGzh4

**Comment by s-kucharski** [comment]
Thank you for the information! Nevertheless, although a comparison of the features of the GL versions is not required as you explained, a structured feature overview in general would be beneficial. Either located in the documentation or in the repository directly.
