### ISSUE TITLE
Default recording visibility should be configurable

### ISSUE THREAD

**Issue by Stoppschildgruen** [bigbluebutton/greenlight#5577]
Addressing [Issue #608](https://github.com/bigbluebutton/greenlight/issues/608) the default recording visibility should be configurable through the Administrator Site Settings.

**Comment by krim404** [comment]
This is a big roadblock due to stringent data protection regulations in europe. At the moment the only possible options are public visible and not published at all - based on the configuration of scalelite. 

Greenlight V3 also added compatibility for protected videos with scalelite. It would also be practical if these options could be preselected, provided that the feature is activated in scalelite. Additionally, it would be excellent if certain user groups, even if they are the room owners, could be prevented from autonomously altering visibility.
