### ISSUE TITLE
Keycloak and greenlight user profiles

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/greenlight#5878]
Hello Devs.

I'm using the keycloak authenticator right now. The keycloak backend is our ldap server. It seems the users cannot edit their usernames in greenlight anymore after the latest keycloak (3.3.6) update. Maybe an earlier release is affected too, don't know exactly. Anyways, here is my question. What could be the reason for the behaviour? Bug in greenlight or is there something which needs to be configured in keycloak or even ldap to get that back working?

cheers! t.

**Comment by fmo1** [comment]
It's not because of Keycloak and it isn't a bug of Greenlight either. 
It was done intentionally... its listed as improvment in in the release notes [3.3.6](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.3.6)
I would say people have different opinions whether it makes sense or not... I don't know the exact reason behind this decision... I'm not part of the dev-team

**Comment by himpierre** [comment]
Thanks for your answers guys!
