### ISSUE TITLE
Sort rooms on the home page alphabetically 

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#700]
For users that have many rooms, it would be easier to locate them if the rooms were displayed across the page in alphabetical order.

**Comment by jfederico** [comment]
I don't think sorting is the right solution for the "users want to locate rooms more easily" request, because it would not be only Sort. What if the user has 100 rooms and the one that is looking for falls in the middle? this would not solve a thing.

Perhaps "Searching" or "Filtering" or "Tagging" or "Grouping"? Or all together?

But either brings a diferent level of complexity to the UI, specially because the original design was not meant to cover masive number of personal rooms. If we were going for sorting, where do we put the sorting option?

I think we have to wait for the new redesign of the entire UI that is on the horizon for 3.0.

**Comment by ffdixon** [comment]
Not too worried about the use case of 100 rooms (that's probably pretty rare).  

The request is more for users that less than a dozen rooms (which is the vast majority).  I think the list of rooms is default unsorted at the moment (new rooms appearing at the end).

The suggestion was to change the default to sorted.  No new UI needed.

**Comment by farhatahmad** [comment]
I agree with Jesus here. Sorting by alphabetical will not solve the issue at hand. In it's core, the issue is essentially that users want to sort their rooms however they want (not however we preset it to). 

With the changes to the rooms page planned in 3.0, I also think its best that we wait until then before implementing this feature.
