### ISSUE TITLE
Registration link in the Invitation emails is incorrect (missing "signup")

### ISSUE THREAD

**Issue by blackie333** [bigbluebutton/greenlight#879]
Hello,
My last issue hopefully :)
After switching the server to invitation mode the emails sent by the admin contain incorrect registration link, missing "signup" page in the link:
It looks like this         : https://servername/b/?invite_token=2yPVsg19UseQT3SxDrYW4PPw
correct link should be: https://servername/b/signup?invite_token=2yPVsg19UseQT3SxDrYW4PPw
Please fix this. Thanks a lot,
Peter

**Comment by blackie333** [comment]
After some changes in the translation it started to work correctly, not sure why the first invitations were missing the signup in the link... Just hope it stays to work as it's now.

I have finished localization to slovak language which I can send to you if you are interested.
Right now I'm checking that it's working fine in parts of GL (including emails)...
At least something I can do in return for you :)

**Comment by farhatahmad** [comment]
Hi @blackie333,

Technically, the first URL is correct. It allows deployments that only use 1 authentication method, to still invite users, since we can't link directly to Google's or Office365's sign up page. 

As for the translations, thank you for taking the time to complete the Slovak translations.
We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/

**Comment by blackie333** [comment]
Thanks for your advice. I have completed and uploaded the translation for BBB server onto transifex and will upload the GL translation too (after it becomes available).
In the meantime I have a problem to test my BBB translation because our bbb installation is missing the "transifex.sh" script.
Could you please help me how to install the script? I don't need full transifex installation on our server, just want to test my BBB translation.
If I just copy my sk_SK.json file to "/usr/share/meteor/bundle/programs/server/assets/app/locales" it becomes available in the client but when I try to and activate it the client starts blinking and not working :(
Thanks a lot

**Comment by capilkey** [comment]
sk_SK was included with BigBlueButton 2.2-RC2 and is selectable. If you update to that BBB version then you should be able to use your own translation file.

The likely reason that it didn't work for you is that new locales also require code changes to function.

**Comment by blackie333** [comment]
Thank you very much, my BBB translation is working now after BBB upgrade :)
Just needed to replace content of the empty installed locale file with my own and it's working - all good.
Now I just need to be member of GL slovak localization group to finish it completely...

**Comment by blackie333** [comment]
Is is possible to chage the default font for bbb? After I apply the locale settings some special characters are displayed in UPPERCASE, please see the attached screenshot:
![image](https://user-images.githubusercontent.com/22171229/70214819-6056cf80-173c-11ea-911e-33dcce69baad.png)

**Comment by capilkey** [comment]
I think the issue is with most accented characters in the version of the font that we are using in BigBlueButton. I think we need to pull a newer version because there have been some bug fixes to it.

The font can be changed, but you'd need to fork the repository and build a custom version of the client. This is all out of scope of Greenlight though and would be better as a mailing list topic https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by blackie333** [comment]
OK, thanks for the information. I see this is out of scope and topic :)
It's not a big problem, I just wanted to note the BBB font issue exists.
I have uploaded the slovak GL translation to transifex, tried my best, hope it's useful for someone.
