### ISSUE TITLE
Greenlight 2.4 "500 Internal Server Error" when only keep other language file

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#893]
After setting admin account, we want to delete en.yml in /usr/src/app/config/locales

Just only keep one language file (without en.yml) for simple management.

But in Greenlight 2.4, if you  rm en.yml and only keep another language, Greenlight cry "500 Internal Server Error"

We had to make a workaround to solve this problem.

If we want to only keep zh_CN.yml， rename zh_CN.yml to en.yml, 
then in row 19
-zh_CN:
+en:

BTW: Greenlight is now mobile-friendly, thanks a lot.

**Comment by farhatahmad** [comment]
I'm not quite sure what the issue here is. If you want to delete a file, you have to delete all the references to that file. The en.yml file is used as the default language file, which is why you can't just remove it and expect it to work right away. 

This is very specific to your deployment and you seem to have got a work around to solve it, so I'll be closing this issue.
