### ISSUE TITLE
Customizing the Landing Page

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#993]
I wanted to Customize the Landing Page and i changed index.html.erb , but when i Restart Greenlight and use docker-compose down i got this error:
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

what should i do?

**Comment by farhatahmad** [comment]
Hi @hmahdi-s,

Are you in the correct directory? Try `cd ~/greenlight` (or wherever you cloned the Github repository)

**Comment by quangbahoa** [comment]
I cannot find app dr on `greenligh`. Just `db` `log` `.env` `docker-compose.yml`

**Comment by hmahdi-s** [comment]
hi @farhatahmad 
thank you.
I went to ~/greenlight by cd command and these two commands work:
  docker-compose down 
,docker-compose up -d

but this one not working:
./scripts/image_build.sh <image name> release-v2
error:
-bash: image: No such file or directory

**Comment by farhatahmad** [comment]
@quangbahoa @hmahdi-s 

You are both using the "Install" version of Greenlight. If you want to Customize the code, follow the instructions here: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

**Comment by quangbahoa** [comment]
> @quangbahoa @hmahdi-s
> 
> You are both using the "Install" version of Greenlight. If you want to Customize the code, follow the instructions here: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Thank you for rep. I did it. But changes are no effect on my greenlight frontend.

**Comment by farhatahmad** [comment]
@quangbahoa I'm going to need a bit more information than that. Whats files are in the Greenlight directory?

**Comment by quangbahoa** [comment]
@farhatahmad  I make some change of `/root/greenlight/app/views/main/index.html.erb` and `/root/greenlight/config/locales/en.yml` eg. change `Welcome to BigBlueButton` to `Welcome to BBB` but no thing change on landing page.

**Comment by farhatahmad** [comment]
@quangbahoa Did you restart Greenlight after the changes? http://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

**Comment by quangbahoa** [comment]
Yea I restart by `docker-compose down` then up `docker-compose up -d`

**Comment by farhatahmad** [comment]
@quangbahoa You're missing a step. Please read the link I sent you

**Comment by quangbahoa** [comment]
> @quangbahoa You're missing a step. Please read the link I sent you

Sorry my bad. After rebuild image nothing change on my landing
```
Successfully tagged bigbluebutton/greenlight:release-v2
#### Docker image for bigbluebutton/greenlight can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)
```

**Comment by farhatahmad** [comment]
Is `bigbluebutton/greenlight` the name you gave it when you ran the install script the first time?

Was this the command you ran `./scripts/image_build.sh bigbluebutton/greenlight release-v2`

Whats the output of `docker ps`

**Comment by quangbahoa** [comment]
Result for `cat docker-compose.yml | grep image:`
```
root@vultr:~/greenlight# cat docker-compose.yml | grep image:
    image: bigbluebutton/greenlight:v2
    image: postgres:9.5
```

Result for `docker ps`
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS                      NAMES
ce69a81d8eec        bigbluebutton/greenlight:v2   "bin/start"              About a minute ago   Up About a minute   127.0.0.1:5000->80/tcp     greenlight-v2
5cffba8b1e5a        postgres:9.5                  "docker-entrypoint.s…"   About a minute ago   Up About a minute   127.0.0.1:5432->5432/tcp   greenlight_db_1
```

**Comment by farhatahmad** [comment]
@quangbahoa You missed some steps when installing.
 
Next, in the docker-compose.yml file, replace:
```
services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
```
With
```
services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:release-v2
```

Then `docker-compose down` and `docker-compose up -d`

**Comment by quangbahoa** [comment]
@farhatahmad  It's work! Thanks so much.

**Comment by wemakefuture** [comment]
Amazing thread! followed the steps. But ending up here: 

Changing it to 

```
services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:release-v2
```

Causes:
```
~/greenlight# docker-compose up -d
Pulling app (bigbluebutton/greenlight:release-v2)...
ERROR: manifest for bigbluebutton/greenlight:release-v2 not found
~/greenlight# nano docker-compose.yml
```
Changing it back to `image: bigbluebutton/greenlight:v2`
Works: 
```
~/greenlight# docker-compose up -d
Creating greenlight_db_1 ... done
Creating greenlight-v2   ... done

```

**Comment by Entretoize** [comment]
Can someone explain me ? You mention ./scripts/image_build.sh but in where directory must it be called ?
The only image_build.sh I have is in /var/lib/docker/overlay2/d0861262372523f3d29e20eead75d981b78f55d11a0a8938b38956c0108b0a89/diff/usr/src/app/scripts/ and it doesn't work with it.

**Comment by Cheyney** [comment]
> Can someone explain me ? You mention ./scripts/image_build.sh but in where directory must it be called ?

In the "greenlight/" directory. Eg: `/root/greenlight`

**Comment by Entretoize** [comment]
Thank you

**Comment by tatangs** [comment]
I get error when
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
`Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - Failed to open TCP connection to mydomain:443 (getaddrinfo: Try again)
`

**Comment by tatangs** [comment]
please help @farhatahmad  when i run 
./scripts/image_build.sh vicon-bp3ip release-v2

`#### Docker image vicon-bp3ip:release-v2 is being built
Sending build context to Docker daemon  4.793MB
Step 1/27 : FROM ruby:2.5.1-alpine AS base
 ---> d29267791323
Step 2/27 : ARG RAILS_ROOT=/usr/src/app
 ---> Using cache
 ---> 2c8ad04f20d0
Step 3/27 : ENV RAILS_ENV production
 ---> Using cache
 ---> 59d36d24e9b0
Step 4/27 : ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"
 ---> Using cache
 ---> 78bec0c63ea6
Step 5/27 : RUN mkdir -p $RAILS_ROOT
 ---> Using cache
 ---> ca54e1d0062f
Step 6/27 : WORKDIR $RAILS_ROOT
 ---> Using cache
 ---> 9c2fa2d6ace0
Step 7/27 : ARG BUILD_PACKAGES="build-base curl-dev git"
 ---> Using cache
 ---> ac04e8747d63
Step 8/27 : ARG DEV_PACKAGES="postgresql-dev sqlite-libs sqlite-dev yaml-dev zlib-dev nodejs yarn"
 ---> Using cache
 ---> 8cba037ca530
Step 9/27 : ARG RUBY_PACKAGES="tzdata"
 ---> Using cache
 ---> fc6b09a99abe
Step 10/27 : RUN apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
 ---> Running in d369b18413a3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 30 distinct packages available
The command '/bin/sh -c apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2
#### Docker image for vicon-bp3ip can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)
`

**Comment by Cistoge** [comment]
@tatangs 

in scripts/image_build.sh, replace the line

docker build --build-arg version_code="${CD_VERSION_CODE}" -t $CD_DOCKER_REPO:$CD_REF_NAME .

with

docker build --network=host --build-arg version_code="${CD_VERSION_CODE}" -t $CD_DOCKER_REPO:$CD_REF_NAME .

**Comment by KurJay** [comment]
> bigbluebutton/greenlight:release-v2

I did change 
from
image: bigbluebutton/greenlight:v2

into
image: bigbluebutton/greenlight:release-v2

After docker-compose up -d there is an error

root@top:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Pulling app (bigbluebutton/greenlight:release-v2)...
ERROR: manifest for bigbluebutton/greenlight:release-v2 not found: manifest unknown: manifest unknown

Regard

**Comment by EliseuDomingos** [comment]
Hello!
I am updating to update the image and get the following information: 



"#### Docker image for bigbluebutton/greenlight can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)"


I already changed docekr
but the error persists. Here is my docker-compose                                                        

version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
"



can someone help me?

**Comment by EliseuDomingos** [comment]
Hello!
I am updating to update the image and get the following information:

"#### Docker image for bigbluebutton/greenlight can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)"

I already changed docekr
but the error persists. Here is my docker-compose

version: '3'

services:
app:
entrypoint: [bin/start]
image: bigbluebutton/greenlight:release-v2
container_name: greenlight-v2
env_file: .env
restart: unless-stopped
ports:
- 127.0.0.1:5000:80

When using external logging
logging:
driver: $LOG_DRIVER
options:
syslog-address: $LOG_ADDRESS
tag: $LOG_TAG
volumes:
  - ./log:/usr/src/app/log
  - ./storage:/usr/src/app/storage
When using sqlite3 as the database
- ./db/production:/usr/src/app/db/production
When using postgresql as the database
links:
  - db
db:
image: postgres:9.5
restart: unless-stopped
ports:
- 127.0.0.1:5432:5432
volumes:
- ./db/production:/var/lib/postgresql/data
environment:
- POSTGRES_DB=postgres
- POSTGRES_USER=postgres
- POSTGRES_PASSWORD=password
"

can someone help me?

**Comment by MeinhartEsrohr** [comment]
same problem here, did you solve the problem @tatangs
